### ISSUE TITLE
nfs mount at boot

### ISSUE THREAD

**Issue by riesebie** [NetworkConfiguration/dhcpcd#100]
How do I manage to mount nfs shares like the if-up.d/mountnfs script does with ifup?

**Comment by rsmarples** [comment]
You can start them with the `/etc/dhcpcd-exit.hook` script. See `dhcpcd-run-hooks (8)` for details.

**Comment by Athanasius** [comment]
As `/etc/network/if-up.d/mountnfs` seems very SysV init centric I decided to roll my own in the `/etc/dhcpcd.exit-hook`.  For others' reference I ended up with:

```bash
#!/bin/sh
# vim: tabstop=4 shiftwidth=4 expandtab smarttab smartindent wrapmargin=0 textwidth=0
#
# dhcpcd exit hooks
#
# NB: Not directly, run, but sourced, by /usr/lib/dhcpcd/dhcpcd-run-hooks
#     and that uses /bin/sh, which is usually dash on Debian.

# set -u

log() {
    printf "%s: $@\n" $(date --iso-8601=seconds) >> /var/lib/dhcpcd/tmp/etc-exit-hook.log
}
###########################################################################
# Ensure any NFS mounts are attempted *after* addresses and routing
# are in place.
###########################################################################
# First check if mounts are already in place.  *Any* active NFS mount counts
mount | grep -E '^([0-9\.]{7,15}|[:0-9a-f]{2-47}):\/[^ ]+ on \/[^ ]+ type nfs ' > /dev/null 2>&1
if [ $? -eq 1 ];
then
# No NFS mounts present
    log "$0: No NFS mounts present"
    # Check this hook run is for expected interface and stage
    # log "$0: interface is: ${interface}"
    if [ "${interface}" = "lan0" ];
    then
        # We don't want to trigger at all stages, only if an address and route
        # has been obtained and added.
        # log "$0: reason is: ${reason}"
        case "${reason}" in
            BOUND|REBIND|REBOOT|BOUND6|REBIND6|REBOOT6|INFORM6)
                log "$0: invoking restart of remote-fs.target"
                systemctl restart remote-fs.target
                ;;
        esac
    fi
# else
#    log "$0: NFS mounts already present"
fi
###########################################################################
```
This works for me, but it is assuming that the various other NFS services are run properly by systemd.

It would, of course, be better if dhcpcd could somehow communicate to systemd that addresses/routes have been added so it can correctly invoke the necessary targets for NFS mounts if applicable.

**Comment by rsmarples** [comment]
> It would, of course, be better if dhcpcd could somehow communicate to systemd that addresses/routes have been added so it can correctly invoke the necessary targets for NFS mounts if applicable.

systemd could listen to addresses and routes being added to the kernel and respond accordingly yes?
dhcpcd does this and systemd likely does to so it's just getting systemd to behave? I don't see the need for any extra API beyond what the kernel offers.

**Comment by Athanasius** [comment]
For the benefit of others, it turns out that the solution is to have `x-systemd.requires=network-online.target` as part of the options on any NFS mount.  This causes the auto-created system target for that mount to have the specified `Requires=` as part of its configuration, so that it's only attempted after this is met.

There is the caveat that systemd seems to consider you online even if only one of IPv4 and IPv6 have an active ... I think it's default route.  In my use case I *had* been using explicit IPv4 addresses for the NFS mounts, but have now changed to a hostname because dhcpcd completes IPv6 setup first.

In my case I'm using the ISC 'KEA' dhcp server software for both DHCP and DHCPv6.

**Comment by perkelix** [comment]
Found via: https://geraldonit.com/2023/02/25/auto-mount-nfs-share-using-systemd/
