### ISSUE TITLE
Tokenised IPv6 Identifiers

### ISSUE THREAD

**Issue by cfilipem** [NetworkConfiguration/dhcpcd#101]
It would be nice to have support in dhcpcd for Tokenised IPv6 Identifiers as described in [draft-chown-6man-tokenised-ipv6-identifiers-02](https://tools.ietf.org/id/draft-chown-6man-tokenised-ipv6-identifiers-02.txt).

**Comment by rsmarples** [comment]
4f56572e8ba1ad673dc4a50d7dceac6ba96b4be6

**Comment by cfilipem** [comment]
Thank you for implementing this feature!
I've been testing it, but it seems not working as expected. The address that dhcpcd is assigning to the network interface is exactly the IPv6 prefix and not the prefix combined with the user specified token.

In https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/ipv6.c
```
        } else if (!IN6_IS_ADDR_UNSPECIFIED(&ifo->token)) {
		*addr = ifo->token;
		return ipv6_makeprefix(addr, prefix, prefix_len);
	}
```
The `ipv6_makeprefix` function is assigning the prefix to the addr and the token is never combined anywhere.

**Comment by rsmarples** [comment]
Sorry about that, should be fixed now.

**Comment by cfilipem** [comment]
Yes, now it works! Thanks.
I found one minor typo in the dhcpcd.conf manpage: https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/dhcpcd.conf.5.in#L658

> token is **combied** with

**Comment by rsmarples** [comment]
Fixed, thanks!
