### ISSUE TITLE
use of the 'inform' option in dhcpcd.conf

### ISSUE THREAD

**Issue by seamusdemora** [NetworkConfiguration/dhcpcd#104]
As I understand it, the advantage of using the `inform` option in favor of the `static value` option comes down to this: 

>The `inform` option causes the DHCP server to provide the default route/gateway addr and DNS address to the client in its ACK message. 

This reduces the chances of an incorrect entry/typo, and is a cleaner, simpler way to secure a fixed IP address. It has also been implied that use of the `inform` option will keep the DHCP client *up-to-date* in the event that DNS or gateway addresses are changed by another (perhaps the network) administrator. However, it would seem this _update_ requires that the DHCPINFORM message be re-sent periodically from the client - is that correct? 

If so, how often does `dhcpcd` re-send its DHCPINFORM notification? Is there a configuration parameter that controls this? If not - does `dhcpcd` rely upon server-initiated `FORCERENEW` messages to effect the updates?  

Thanks for your enlightenment :)
~S

**Comment by rsmarples** [comment]
DHCP INFORM is effectively a one time deal.
FORCERENEW will indeed trigger another INFORM being sent.
