### ISSUE TITLE
I: dhcpcd5: spelling-error-in-binary usr/sbin/dhcpcd addres address

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#105]
On dhcpcd version 9.4.1, Lintian reports:

I: dhcpcd5: spelling-error-in-binary usr/sbin/dhcpcd addres address

**Comment by rsmarples** [comment]
Hmmmm, grepping the code for that returns no hits. Can you provide any more information about this please?

**Comment by perkelix** [comment]
N:
I: spelling-error-in-binary
N:
N:   Lintian found a spelling error in the given binary. Lintian has a list
N:   of common misspellings that it looks for. It does not have a
N:   dictionary like a spelling checker does.
N:   
N:   If the string containing the spelling error is translated with the
N:   help of gettext or a similar tool, please fix the error in the
N:   translations as well as the English text to avoid making the
N:   translations fuzzy. With gettext, for example, this means you should
N:   also fix the spelling mistake in the corresponding msgids in the *.po
N:   files.
N:   
N:   You can often find the word in the source code by running:
N:   
N:    grep -rw <word> <source-tree>
N:   
N:   This tag may produce false positives for words that contain non-ASCII
N:   characters due to limitations in strings.
N:   
N:   Severity: info
N:   
N:   Check: binaries
N:

$ grep -rw addres
$

It could also be a false positive.

**Comment by perkelix** [comment]
I haven't seen this in any recent build. Closing.
