### ISSUE TITLE
please add support for systemd's timesyncd

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#106]
version: 9.4.1

The current NTP hook (50-ntp.conf) provides seamless support for NTP, OpenNTP and Chrony (in that order).

It would be desirable to add support for systemd's built-in NTP client (timesyncd).

The enclosed files currently used at Debian may provide useful starting points for this.

[60-ntp-common.conf.txt](https://github.com/NetworkConfiguration/dhcpcd/files/8993175/60-ntp-common.conf.txt)
[64-timesyncd.conf.txt](https://github.com/NetworkConfiguration/dhcpcd/files/8993176/64-timesyncd.conf.txt)

**Comment by perkelix** [comment]
A different approach found on the [Raspberry Pi forum](https://forums.raspberrypi.com/viewtopic.php?p=1340336#p1340336).

# Set NTP servers for systemd-timesyncd
confd=/run/systemd/timesyncd.conf.d
set_servers() {
    mkdir -p "$confd"
    (
        echo "# Created by dhcpcd hook"
        echo "[Time]"
        echo "NTP=$new_ntp_servers"
    ) > "$confd/dhcp-ntp.conf"
    # Tell timesyncd it has an updated configuration
    systemctl try-reload-or-restart systemd-timesyncd
}
if $if_up; then
    set_servers
fi

**Comment by rsmarples** [comment]
#6ab00c2de58936b30be48611e9d402ad51de5abb and #c872b2d6e074e71a622be8be5318989c7b83240b are follow on patches.

**Comment by rsmarples** [comment]
6ab00c2de58936b30be48611e9d402ad51de5abb and c872b2d6e074e71a622be8be5318989c7b83240b are follow on patches.
