### ISSUE TITLE
typo in hooks manual page

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#110]
Version: 9.4.1

dhcpcd-run-hooks.8 has a typo. We really mean the possessive its, not the contraction it's. Patch attached.

[diff.txt](https://github.com/NetworkConfiguration/dhcpcd/files/9032591/diff.txt)

**Comment by rsmarples** [comment]
Thanks for the patch!

**Comment by perkelix** [comment]
Could all typo fixes to the manual page be ported over to branch 9 as well?
