### ISSUE TITLE
dhcpcd should check the HW addr in a stored lease file

### ISSUE THREAD

**Issue by semihalf-ostruszka-andrzej** [NetworkConfiguration/dhcpcd#117]
Hi

I would like to confirm one thing before I start to work on it.
I believe dhcpcd should be checking if the HW address that is stored in the lease file matches current value of the address of the interface and if it doesn't then the lease should be ignored and normal discovery should be started.

Do you agree?

If so then my plan is to add this check in `dhcp_start1()`.

With regards
Andrzej

**Comment by rsmarples** [comment]
No, this is not a good idea.
dhcpcd creates a DUID based of a hardware address and the current time and stores it in a file for all future runs.
If then sends this + interface index as the ClientID.
It's also a touch more complex for DHCPv6.

So it doesn't really matter if the hardware address changes as DHCP messages are not strictly bound to it.

**Comment by semihalf-ostruszka-andrzej** [comment]
Thank you for the reply Roy, and apologies for the delay (was on vacations).

The context is MAC randomization for WiFi in Chrome OS.  In certain situations we will periodically change MAC for the same network and we wanted to avoid situation that by starting dhcpcd after MAC change it would reveal the identity by sending REQUEST with previously stored IP (when the lease is still valid).  We do not use DUID (using "clientid" in config file) but I guess there is a tension here between this randomization (for privacy reasons) and DHCP (which tries to identify given client to maximy IP reuse) and this would be easier to handle outside of the dhcpcd just by deleting the lease file.

Thanks.

**Comment by rsmarples** [comment]
Read the anonymous option in the fine dhcpcd.conf(5) manual page:

```
     anonymous
             Enables Anonymity Profiles for DHCP, RFC 7844.  Any DUID is
             ignored and ClientID is set to LL only.  All non essential
             options are then masked at this point, but they could be unmasked
             by explicitly requesting the option after the anonymous option is
             processed.  As such, the anonymous option should be the last
             option in the configuration unless you really want to send
             something which could identify you.  dhcpcd will not try and
             reboot an old lease, it will go straight into DISCOVER/SOLICIT.
```

This should address your concern and you won't need to do anything - nothing in the leasefile will be sent.
In this case, the lease file would be to remove any active configuration on the client such as old IP address/routes, etc.

**Comment by semihalf-ostruszka-andrzej** [comment]
Thanks for the pointer.  Will look at this.
