### ISSUE TITLE
Ethernet only works after reboot

### ISSUE THREAD

**Issue by DasLixou** [NetworkConfiguration/dhcpcd#118]
so me having this problem that when i boot into linux my ethernet doesnt work, but when i `sudo restart`, then ethernet connects.

 when i start it the first time and get the status from dhcpcd via systemctl it says 2 times "no valid interfaces found", then "carrier aquired" then some logs about an ipv6 iguess and then it says "carrier lost". after the reboot when i printed the status and it directly says "carrier aquired" and worked.
![2D6D86EF-0307-44F0-9636-43DEBF653B0E](https://user-images.githubusercontent.com/82600264/182443439-e7a3c5d4-5c1c-46db-98f7-9954eba9a1b4.jpeg)
![A6D1585F-81D4-4F00-B54C-4CB974F48EA0](https://user-images.githubusercontent.com/82600264/182443466-d369c32b-aa0b-46dc-9212-28d97c9c1f9c.jpeg)

**Comment by rsmarples** [comment]
I'm not entirely clear what the issuse is here. Are you saying that booting the computer from a cold start causes dhcpcd not to find the interface but rebooting the computer then allows it to work?

**Comment by DasLixou** [comment]
> I'm not entirely clear what the issuse is here. Are you saying that booting the computer from a cold start causes dhcpcd not to find the interface but rebooting the computer then allows it to work?

.. yes 🤣. I ask in a discord from a YouTuber which I followed a windows Dual boot install and the vid creator has the same problem. Seems like it is smth with dual booting with windows. But I don’t know why dhcpcd doesn’t find the interface then

**Comment by rsmarples** [comment]
Weird. I'm going on holiday for a few weeks so can't help more until I get back, but this smells like a udev issue.

On systems without udev, dhcpcd listens to kernel data to say "here is an interface and this is it's state."
On systems with udev, dhcpcd needs to listen to kernel data to find the interface and state, but needs to wait until udev announces that the interface is ready.

If I'm right, you can probably fix this by disabling interface renaming in udev and adding the nodev directive at the top of `dhcpcd.conf`.

**Comment by DasLixou** [comment]
Worked! had to set `net.ifnames=0` as a kernel variable.
