### ISSUE TITLE
DNS server added to wrong interface in VLAN setup

### ISSUE THREAD

**Issue by exploide** [NetworkConfiguration/dhcpcd#119]
I tried to use dhcpcd to connect to a VLAN tagged network. Most of it works, but the DNS server is added to the physical interface instead of the VLAN specific interface.

I'm running the following commands:

```console
$ ip l add link enp2s0u4 name enp2s0u4.72 type vlan id 72

$ ip l set dev enp2s0u4.72 up

$ dhcpcd enp2s0u4.72
```

Then I run `resolvectl` to see the DNS config:

```console
$ resolvectl
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp1s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp7s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.100.1
       DNS Servers: 192.168.100.1
        DNS Domain: internal

Link 4 (enp2s0u4)
Current Scopes: LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
   DNS Servers: 192.168.72.254

Link 5 (enp2s0u4.72)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

The first two interfaces don't matter, these belong to the VM. But the correct DNS server for the VLAN (192.168.72.254) is added to the physical interface `enp2s0u4` instead of the VLAN tagged interface `enp2s0u4.72`.

This completely breaks DNS, because the server is not used. It might also play a role that the `DefaultRoute` setting is turned off here. I think this is systemd-resolved specific.

If I configure the VLAN via NetworkManager instead, everything ends up correctly. This is the proper `resolvectl` output:

```console
$ resolvctl 
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp1s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (enp7s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.100.1
       DNS Servers: 192.168.100.1
        DNS Domain: internal

Link 4 (enp2s0u4)
Current Scopes: LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (enp2s0u4.72)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.72.254
       DNS Servers: 192.168.72.254
```

Here, the DNS server is configured for the VLAN tagged interface and the `DefaultRoute` setting is turned on.

It would be awesome if dhcpcd could support per-interface DNS in VLAN setups and systemd-resolved, as it becomes more and more common.

**Comment by rsmarples** [comment]
This is likely a bug with the `resolvconf` shim they have where they treat what is after the first dot as a protocol rather than the last.
https://github.com/systemd/systemd/blob/aea29a300d14d183ef9a2f946a36d0631a6b2d0d/src/resolve/resolvectl.c#L136

As you can see, given the interface name `enp2s0u4.72.dhcp` it would take `72.dhcp` as the protocol and `enp2s0u4` as the name.

The workaround would be to give the vlan interface a name without a period.

**Comment by exploide** [comment]
Thanks for your fast reply. I think you are right.

I found issue https://github.com/systemd/systemd/issues/20014 and PR https://github.com/systemd/systemd/pull/20015 where this behavior was changed to only affect invocations of `resolvconf`. Prior to this it also affected `resolvctl`.

I opened PR https://github.com/systemd/systemd/pull/24274 to propose removing everything behind the last dot only. Let's see.
