### ISSUE TITLE
SIGSYS from SECCOMP clock_nanosleep on exit

### ISSUE THREAD

**Issue by phibreDE** [NetworkConfiguration/dhcpcd#128]
I noticed that my dhcpcd always coredumps with SIGSYS on exit.
@rsmarples, you mentioned in https://github.com/NetworkConfiguration/dhcpcd/commit/3b294661fb106a6075654d6404e846df3438821e (see also #127) that "This means that we no longer need to allow nanosleep in SECCOMP.".

I found out that my SIGSYS is the result of a missing seccomp filter for the syscall `clock_nanosleep`. It seems like glibc changed the underlying syscall from `nanosleep` to `clock_nanosleep` some versions ago (see this 2020-08 [glibc issue](https://sourceware.org/bugzilla/show_bug.cgi?id=26540)).
I'm running current Arch Linux with glibc 2.36-3.

I compiled dhcpcd with the above patch and the syscall `clock_nanosleep` is still used.
So based on this, I'm not sure if dropping `nanosleep` in SECCOMP would result in SIGSYS errors on older glibc versions or other C implementations if supported here.
However, the syscall `clock_nanosleep` must be added to the seccomp filter to mitigate exit crash on recent operating systems.

**Comment by rsmarples** [comment]
Looks like I just missed one nanosleep call.
Removing it is trivial, just please wait for a bit as it has unconvered another issue I would like to fix and this is a good reminder.
