### ISSUE TITLE
Please add an option to only install an IPv4 (or IPv6) default gateway for the same interface

### ISSUE THREAD

**Issue by WRMSRwasTaken** [NetworkConfiguration/dhcpcd#134]
Given the following configuration, I was trying to request an IPv4 via DHCP with a default route, and an IPv6 subnet but without a default route (because this is being handled by policy based routing in different tables due to me having multiple IPv6 upstreams):

```
allowinterfaces eth2
interface eth2
  ipv4only

interface eth2
  ipv6only
  nogateway
  ia_na 0
  ia_pd 0 br1/0/64
```

Unfortunately, this does not work as you can't specify an interface multiple times in the options and I had to work-around this by setting `nogateway` in one big block, removing the `ipv4only` and `ipv6only` and adding a hook script with some magic to add an IPv4 default route this way.

Would it be possible to add (for example) `noipv4gateway` and `noipv6gateway` options to dhcpcd.conf? Thanks.

**Comment by rsmarples** [comment]
Would `nopiv6rs` work for you? That will stop the default IPv6 route.

**Comment by WRMSRwasTaken** [comment]
Yes, that did the trick for me.

```
interface eth2
  noipv6rs # we don't want a default route
  ia_na 0
  ia_pd 0 br1/0/64
```

 I haven't actually thought much about that option to be honest. Thanks!
