### ISSUE TITLE
Request new release tag

### ISSUE THREAD

**Issue by phibreDE** [NetworkConfiguration/dhcpcd#135]
Hi,

the latest release tag is from 22 October 2021.

Since then there were several problems addressed for example with privilege separation on newer glibc versions.
I'm not sure how many Linux distributions are affected by this (at least Arch Linux is), but I would like to see these fixes getting to downstream.

So actually the purpose of this issue is to request a new release tag.

If help is needed, please let me know.

**Comment by rsmarples** [comment]
Yes, this is long overdue.

**Comment by perkelix** [comment]
Are we getting any closer to this? Do you need any help to produce the release?

**Comment by rsmarples** [comment]
Aside from fixing #149 we are good to go I think.

**Comment by perkelix** [comment]
> Aside from fixing #149 we are good to go I think.

Then let's proceed.

The sheer number of commits since 9.4.1 has turned cherry-picking fixes into a risky game. We really need that release now.

**Comment by rsmarples** [comment]
And we now have a new release.
