### ISSUE TITLE
Routing problem with certain prefix length

### ISSUE THREAD

**Issue by cby120** [NetworkConfiguration/dhcpcd#137]
Dear developer: 

Hello ! 

I'm encountered with a problem. I'm using a Debian host as a soft router for several devices. My ISP is China Mobile corp. and I'm able to acquire IPv6 addresses and prefixes. However, the prefix length I receive is usually ::/60. At such circumstance, dhcpcd will assign a ::/64 prefix to my LAN interface br0, but **adding a route to ::/60 network into the route table**, which is always marked **Unreachable**. If I manually add a route to the correct ::/64 network via br0, everything works just fine. Beside this, the route added is set as **via lo**, the localhost interface, which ought to be **br0**, the interface of LAN who is asking for an IPv6 address to be assigned with. I'm confused if dhcp client can deal with such sitiation and route the network prefix it assigns instead of what it receives from ISP. 

My dhcpcd version is **7.1.0** from Debian's apt source, and my system is **Debian 5.10**. I use PPPoE for Internet access. I want to acquire an IPv6 prefix for my LAN interface br0, and add the routing rule: **to the assigned ::/64 net segment via br0** to the route table of Debian host. The corresponding part of dhcpcd configuration is as follow:
```
slaac private
interface ppp0
ipv6rs
iaid 1
ia_pd 2 br0
```

I'm not quite familiar with network setups, so I tend to believe this problem is caused by my misunderstanding or wrong configuration. If so, I really need some hint. If any information missing please let me know. Thank you very much !

**Comment by cby120** [comment]
Maybe I should post some log here: 
```
root@server:~# ifconfig
> br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
           inet 192.168.1.1  netmask 255.255.255.0  broadcast 192.168.1.255
           inet6 fe80::4c9b:8773:1f42:1f0c  prefixlen 64  scopeid 0x20<link>
           inet6 2409:8a14:11b3:1c8d::1  prefixlen 64  scopeid 0x0<global>

root@server:~# ip -6 route
> unreachable 2409:8a14:11b3:1c80::/60 dev lo proto dhcp metric 201 pref medium
> 2409:8a14:11b3:1c8d::/64 dev br0 metric 1024 pref medium
```

log from dhcpcd, I marked the lines that may be useful by [> xxxx <]: 
```
Oct 11 22:11:17 server dhcpcd[3940]: br0: IAID 26:7e:08:96
Oct 11 22:11:17 server dhcpcd[3940]: br0: soliciting a DHCPv6 lease
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: IAID 00:00:00:01
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: IA type 25 IAID 00:00:00:02
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: rebinding prior DHCPv6 lease
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: soliciting an IPv6 router
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: soliciting an IPv6 router
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: Router Advertisement from fe80::8a66:39ff:fe8d:f050
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding address 2409:8a14:110b:45a1:xxxx:xxxx:xxxx:xxxx/64
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: Router Advertisement from fe80::8a66:39ff:fe8d:f050
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding address 2409:8a14:110b:45a1:xxxx:xxxx:xxxx:xxxx/64
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding route to 2409:8a14:110b:45a1::/64
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding default route via fe80::8a66:39ff:fe8d:f050
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding route to 2409:8a14:110b:45a1::/64
Oct 11 22:11:17 server dhcpcd[3940]: ppp0: adding default route via fe80::8a66:39ff:fe8d:f050
Oct 11 22:11:18 server dhcpcd[3940]: ppp0: REPLY6 received from fe80::8a66:39ff:fe8d:f050
Oct 11 22:11:18 server dhcpcd[3940]: ppp0: renew in 86400, rebind in 138240, expire in 259200 seconds
Oct 11 22:11:18 server dhcpcd[3940]: ppp0: REPLY6 received from fe80::8a66:39ff:fe8d:f050
> Oct 11 22:11:18 server dhcpcd[3940]: lo: adding reject route to 2409:8a14:11b3:1c80::/60 <
> Oct 11 22:11:18 server dhcpcd[3940]: ppp0: delegated prefix 2409:8a14:11b3:1c80::/60 <
> Oct 11 22:11:18 server dhcpcd[3940]: br0: adding address 2409:8a14:11b3:1c8d::1/64 <
Oct 11 22:11:18 server dhcpcd[3940]: ppp0: renew in 86400, rebind in 138240, expire in 259200 seconds
> Oct 11 22:11:18 server dhcpcd[3940]: lo: adding reject route to 2409:8a14:11b3:1c80::/60 <
Oct 11 22:11:18 server dhcpcd[3940]: ppp0: delegated prefix 2409:8a14:11b3:1c80::/60
> Oct 11 22:11:18 server dhcpcd[3940]: br0: adding address 2409:8a14:11b3:1c8d::1/64 <
```

**Comment by perkelix** [comment]
7.1.0 is really old. You might wanna try 9.4.1 from Debian/Testing.

**Comment by cby120** [comment]
Upgrading has successfully solve the problem. Thank you so much !
If not too complicated, whould you mind explaining why it is necessary to add the [unreachable IPv6 ::/60 prefix] to the route table ?

**Comment by rsmarples** [comment]
By adding a reject route we can tell any incoming request for a route in our prefix we haven't assigned - such as a request to 2409:8a14:11b3:1c8e::1 - that it doesn't exist faster because your router doesn't have to try and find the non-existant host,

**Comment by cby120** [comment]
I get it. Thank you again !
