### ISSUE TITLE
./configure fails using GNU autotools

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#139]
The defaults in the ./configure script that comes with dhcpcd 9.4.1 are broken. The script is behaving like PREFIX=/:

```
 $ fakeroot debian/rules install && find debian/tmp -path '*man*'
    debian/tmp/share/man/man8/dhcpcd-run-hooks.8
```
The problem is that dh_auto_configure invokes configure like for a standard GNU autotools:
```
./configure [...] --prefix=/usr --mandir=\${prefix}/share/man
```
But `$prefix` is not defined inside ./configure, it uses the variable `$PREFIX` instead. This also affects all other default paths.

**Comment by rsmarples** [comment]
Let us be clear - the configure script is not broken at all as it's worked happily on any OS's, Debian included.

It could be argued that Debians reliance on configure setting a prefix variable is broken as you could write
`prefix=/usr ./configure --prefix=${prefix} --mandir=${prefix}/share/man`

And not have to worry about any inner workings.

BTW, the configure uses prefix as many other popular packaging systems set PREFIX in the environment and expect things to respect that.

**Comment by perkelix** [comment]
No, dhcpcd's configure script does NOT happily work on Debian, since it doesn't accept the standard GNU prefix. As a result, without explicitly configuring the manual path, it ends up in `/share/man/man8/dhcpcd-run-hooks.8` using upstream configure's defaults.

**Comment by rsmarples** [comment]
Without explicity configuring the manual path.

```
./configure --prefix=/a/test
...
   MANDIR =             /a/test/share/man
```

Looks correct to me. Maybe something else in your enviornment is affecting things?

**Comment by rsmarples** [comment]
Oh that was on a Debian machine. Maybe it's something in Debian's packaging system that does this?

**Comment by rsmarples** [comment]
Does that fix your issue? It seems to work but I can't readily test it.

**Comment by perkelix** [comment]
> Oh that was on a Debian machine. Maybe it's something in Debian's packaging system that does this?

Read the above again. What happens is fairly clear. Please note that other Linux distributions also end up having to manually specify the full manual path, for the reasons already stated.

**Comment by martinpitt** [comment]
Thanks @rsmarples ! [That fix](https://github.com/NetworkConfiguration/dhcpcd/commit/6a9994bbf00712ac) works well!

**Comment by perkelix** [comment]
> Does that fix your issue? It seems to work but I can't readily test it.

Yes, this works well. Thanks!

**Comment by stappersg** [comment]
> > Does that fix your issue? It seems to work but I can't readily test it.

Fix being commit [https://github.com/NetworkConfiguration/dhcpcd/commit/6a9994bbf00712ac](https://github.com/NetworkConfiguration/dhcpcd/commit/6a9994bbf00712ac)

> Yes, this works well. Thanks!

@perkelix  do know that you can close this issue because you have opened it.

And frankly: _You should have closed it already._
