### ISSUE TITLE
systemctl hooks could use --no-block

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#141]
On Debian's homebrewed timesyncd hook, we received a bug report that it should use systemctl's option --no-block.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003225

https://blog.oddbit.com/post/2014-12-02-starting-systemd-services-with/

It would be desirable for all dhcpcd exit hooks that call systemctl to use that option.

**Comment by rsmarples** [comment]
Does `--no-block` work when you stop a service as well? If you could test that and let me know it makes the fix easier.

**Comment by perkelix** [comment]
As far as I can tell from this, it would:

https://www.freedesktop.org/software/systemd/man/systemctl.html

--no-block

Do not synchronously wait for the requested operation to finish. If this is not specified, the job will be verified, enqueued and systemctl will wait until the unit's start-up is completed. By passing this argument, it is only verified and enqueued. This option may not be combined with --wait.

**Comment by perkelix** [comment]
As an example, this is how Debian's current hook was modified:

https://salsa.debian.org/debian/dhcpcd5/-/commit/7ca3cf324f417136731f42a3b2d63983e595d878
