### ISSUE TITLE
How to make the scripts run under /usr/lib/dhcpcd/dhcpcd-hooks/

### ISSUE THREAD

**Issue by Mingli-Yu** [NetworkConfiguration/dhcpcd#144]
```
After put some scripts under  /usr/lib/dhcpcd/dhcpcd-hooks/ as below:
# ls /usr/libexec/dhcpcd-hooks/
01-test  20-resolv.conf  30-hostname  50-ntp.conf

I want to update both /etc/resolv.conf and /etc/ntp.conf during execute "dhcpcd", but it seems it can only update /etc/ntp.conf via "dhcpcd -e new_ntp_servers=xxx.xxx.xxx.xxx". 
That means I must pass new_ntp_servers variable if want to update /etc/ntp.conf. Is that the expected behavior?  

BTW, I didn't update /etc/resolv.conf successfully even pass the variable new_domain_name_servers. How can I update /etc/resolv.conf? Thanks!

```

**Comment by rsmarples** [comment]
It means that the DHCP message you received did not include any NTP servers.

The hook `20-resolv.conf` might not update `/etc/resolv.conf` if it finds a `resolvconf` program. It will call that and `resolvconf` will deal with it from there.

**Comment by Mingli-Yu** [comment]
> It means that the DHCP message you received did not include any NTP servers.

Does it mean I don't need to set  "-e new_ntp_servers=xxx.xxx.xxx.xxx" if the DHCP message message include NTP servers? Actually I config ntp server info in dhcp server config /etc/dhcp/dhcpd.conf. 


> 
> The hook `20-resolv.conf` might not update `/etc/resolv.conf` if it finds a `resolvconf` program. It will call that and `resolvconf` will deal with it from there.

No matter the hook `20-resolv.conf`  change it directly or call the program resolvconf to change it. What I observed is the /etc/resolve.conf didn't change after execute "dhcpcd -e new_domain_name_servers xxx.xxx.xxx.xxx".

**Comment by rsmarples** [comment]
If you want to set static NTP servers I suggest you do that outside of dhcpcd.
