### ISSUE TITLE
dhcpcd incorrectly removes DNS records

### ISSUE THREAD

**Issue by ChenQi1989** [NetworkConfiguration/dhcpcd#146]
Version:
3c458fc7fa4146029a1e4f9e98cd7e7adf03081a (tag: dhcpcd-9.4.1)

Environment:
qemu + slirp network + dhcpcd + systemd-resolved

Behavior:
dhcpcd first correctly configures DNS via resolvconf, then it removes the records, resulting in incorrect /etc/resolv.conf.

Output from 'journalctl | grep 10.0.2'
  Nov 01 05:32:12 qemux86-64 dhcpcd[233]: eth0: rebinding lease of 10.0.2.15
  Nov 01 05:32:12 qemux86-64 dhcpcd[233]: eth0: leased 10.0.2.15 for 86400 seconds
  Nov 01 05:32:12 qemux86-64 dhcpcd[233]: eth0: adding route to 10.0.2.0/24
  Nov 01 05:32:12 qemux86-64 dhcpcd[233]: eth0: adding default route via 10.0.2.2
  **Nov 01 05:32:12 qemux86-64 systemd-resolved[188]: eth0: Bus client set DNS server list to: 10.0.2.3**

I added a few debug messages in dhcpcd-hooks/20-resolv.conf.
Output from 'journalctl | grep qi'
  Nov 01 05:32:11 qemux86-64 dhcpcd-systemd-wrapper[255]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:11 qemux86-64 dhcpcd-systemd-wrapper[255]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:11 qemux86-64 dhcpcd-systemd-wrapper[264]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:11 qemux86-64 dhcpcd-systemd-wrapper[264]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:12 qemux86-64 dhcpcd-systemd-wrapper[334]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:12 qemux86-64 dhcpcd-systemd-wrapper[334]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  Nov 01 05:32:15 qemux86-64 dhcpcd-systemd-wrapper[362]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true
  **Nov 01 05:32:15 qemux86-64 dhcpcd-systemd-wrapper[362]: [qi]: running remove_resolv_conf
  Nov 01 05:32:15 qemux86-64 dhcpcd-systemd-wrapper[362]: [qi]: running resolvconf -d eth0.ra -f**
  Nov 01 05:32:15 qemux86-64 dhcpcd-systemd-wrapper[362]: [qi]: dhcpcd resolv.conf hook is run, have_resolvconf=true

We can see that at 05:32:12, dhcpcd gave systemd-resovled the correct DNS information, but 3 seconds later, at 05:32:15, dhcpcd ran the hook again and removed the records.

Looking at the codes in 20-resolv.conf, the related codes are:
        # If we don't have any configuration, remove it
        if [ -z "$new_domain_name_servers" ] &&
           [ -z "$new_domain_name" ] &&
           [ -z "$new_domain_search" ]; then
                        remove_resolv_conf

I think in some cases, the hook script is run and the above three vars are empty. Note that I didn't do any special configuration, just a normal qemu slirp boot.

Is it a bug? Is it possible to make 20-resolv.conf distinguish the situation where a removal is needed and where it's not. Or should we just return there early instead of do remove_resolv_conf? If so, what could be the potential impact?

**Comment by ChenQi1989** [comment]
Some more info:
I removed the remove_resolv_conf line and make the script return there, and things are working as expected.

root@qemux86-64:~# grep -v '#' /etc/resolv.conf
nameserver 10.0.2.3
search .

**Comment by ChenQi1989** [comment]
I've further tracked down the problem to be IPv6 RA.

See logs below:
Nov 09 08:14:31 qemux86-64 dhcpcd[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:31 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:30 qemux86-64 dhcpcd[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:30 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:14:29 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: pltime 14400 seconds, vltime 86400 seconds
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: adding address fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:29 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: sending NA for fec0::b98e:c7ca:b857:39d7/64
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: Router Advertisement from fe80::2

And we have:
root@qemux86-64:~# journalctl | grep dhcpcd-run-hooks
Nov 09 08:10:52 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks PREINIT
Nov 09 08:10:52 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks PREINIT
Nov 09 08:10:52 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks CARRIER
Nov 09 08:10:52 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks CARRIER
Nov 09 08:10:53 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks REBOOT
Nov 09 08:10:53 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks REBOOT
Nov 09 08:10:54 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:10:54 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:14:29 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:14:29 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:22:04 qemux86-64 dhcpcd-systemd-wrapper[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT
Nov 09 08:22:04 qemux86-64 dhcpcd[213]: eth0: executing: /usr/libexec/dhcpcd-run-hooks ROUTERADVERT

**Comment by ChenQi1989** [comment]
https://www.rfc-editor.org/rfc/rfc8106:
  """
   These issues are not pressing in dual-stack networks as long as a DNS
   server is available on the IPv4 side, but they become more critical
   with the deployment of IPv6-only networks.  As a result, this
   document defines a mechanism based on DNS RA options to allow IPv6
   hosts to perform automatic DNS configuration.
  """

According to the above statements, automatic DNS configuration is optional in IPv6 RA, as long as IPv4 has got DNS information.
So I think we should just early return in case "$reason" is "ROUTERADVERT".

**Comment by rsmarples** [comment]
This is a systemd issue here: https://github.com/systemd/systemd/issues/25032

**Comment by ChenQi1989** [comment]
@rsmarples Thanks for your reply. But I'm a little confused. Why is this related to above systemd issue?
You can see from the above logs that the DNS is correctly set when running "/usr/libexec/dhcpcd-run-hooks CARRIER", and then when running "/usr/libexec/dhcpcd-run-hooks ROUTERADVERT", the remove_resolv_conf is invoked and the entries are removed.
I'm not a network expert, but reading https://www.rfc-editor.org/rfc/rfc8106, it seems that IPv6 RA may not carry DNS info and it's valid.
I also saw your comments in https://github.com/NetworkConfiguration/dhcpcd/pull/151, but I think we have some misunderstanding here. IPv6 RA never gives us some DNS info in this case. From the logic of your comment in pull request 150, I think the DNS records should be removed when running '/usr/libexec/dhcpcd-run-hooks CARRIER' again, because this is what sets the DNS, not the ROUTERADVERT. What do you think?

**Comment by ChenQi1989** [comment]
@rsmarples Hi Roy, I used 'qemu + slirp' in the description to describe the environment, but this is not limited to qemu. 'Internal DHCP server + DNS server + real boards + dhcpcd' can also reproduce this issue. I used 'qemu + slirp' in description because I think it's a convenient way to reproduce the issue.

**Comment by ChenQi1989** [comment]
@rsmarples  Thanks for the clarification! This is the typical situation that reminds of the controversial reputation of systemd.
I also found that 20-resolv.conf can build resolv.conf itself, so I can we can rely on this ability and then just supply the generated file to systemd's resolvconf. This way, 'dhcpcd + systemd' could work together. I've created https://github.com/NetworkConfiguration/dhcpcd/pull/152. Hope this could improve the situation a little bit.

**Comment by rsmarples** [comment]
No we cannot rely on this.
If resolvconf is installed, other things might rely on it returning correct data rather than `/etc/resolv.conf` being correct.

Upstream resolvconf needs to either be fixed or removed.
If either is not possible then system distros need to sort this out for themselves, it's not being fixed here.
