### ISSUE TITLE
Prefix delegation updates failing after link loss and recovery on WAN

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#154]
As reported at [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023728):

'''Set up multiple LANs with prefix delegation from WAN using ia_pd with an explicit list of interaces to delegate to. Initial dhcp startup works fine, prefixes get delegated as expected. When the WAN link is lost the delegated addresses are removed as expected. After the link recovers the delegation does not work properly. 

Root cause: In dhcp6_delegate_prefix is a loop over all interfaces in the context. As the delegated prefixes are assigned the interface order is changing (e.g., due to DAD being executed for the newly assigned prefix which changes interface priority). This causes the loop to skip other LAN interfaces.

Solution that worked for me: Replace the loop with a "_SAFE" variant. This will likely process interfaces twice but this has no negative side effects.'''

A proposed patch is attached to the Debian bug.

**Comment by rsmarples** [comment]
My one second review tells me this might not fix all cases. I think what we really need to do is to remove sorting interfaces in the context and if any sorting is required, do this at the protocol level.

**Comment by wteiken** [comment]
Yeah, hence my "works for me" comment in the original bug report. I had considered various alternatives including moving all the modifications past the interface loop.

**Comment by rsmarples** [comment]
@wteiken I'm pretty sure this is not needed in dhcpcd-9 as we have removed interface sorting already. As was noted in the Debian bug report it seems you're running a very old version?

**Comment by perkelix** [comment]
@wteiken As requested earlier, can you tell us whether 9.4.1 fixes it for you?

**Comment by wteiken** [comment]
Confirmed, the 9.4.1 from the debian testing branch seems to properly set the delegation for all interfaces once the connection is back up. Some issues with TIMEOUT6 if the DHCP server is not immediately responding, but I am still investigating that and will file a separate bug if I figure it out.

Thanks!
