### ISSUE TITLE
Memory leak on interface reconfiguration

### ISSUE THREAD

**Issue by grahamw-veea** [NetworkConfiguration/dhcpcd#157]
Present in 9.4.1, originally detected in 7.0.8.

In an application which uses a lot of interfaces with some being frequently added and deleted, I have seen dhcpcd memory usage grow by about 1MB per hour.

The source of this leak appears to be:

dhcpcd_handleinterface() calls if_discover(), which in turn calls getifaddrs(), allocating a new "struct ifaddrs".

dhcpd_handleinterface() assumes that this memory will be freed inside the call to if_learnaddrs() later in the function. However, that can be bypassed by the "goto out" a few lines down, and can also be bypassed if action == 0. If either of those things happen, the memory is leaked.

Suggested fix: initialize "ifaddrs" to NULL in dhcpcd_handleinterface(). Add a call to freeifaddrs() in the "out:" block if "ifaddrs" is not NULL.

**Comment by rsmarples** [comment]
We need our own function as we may have gotten ifaddrs via privsep.
Thanks for identifying the issue!
