### ISSUE TITLE
compiler warnings (GCC 12 binutils 2.39) on Linux

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#163]
Building dhcpcd 9.4.1 wih GCC 12.2.0 and binutils 2.39.90 on Debian/Linux produces the attached compiler warnings.

[dhcpcd5_9.4.1-12_i386_build.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10368281/dhcpcd5_9.4.1-12_i386_build.txt)

**Comment by rsmarples** [comment]
Can you post the content of config.log pertinent to finding arc4random please?

Looks like it's been added to glibc but configure is not finding it.

**Comment by perkelix** [comment]
[config.log](https://github.com/NetworkConfiguration/dhcpcd/files/10368878/config.log)

**Comment by perkelix** [comment]
[config_log.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10368935/config_log.txt)

**Comment by rsmarples** [comment]
Can you test the commit on the above branch to see if it fixes your issue please?

**Comment by perkelix** [comment]
This is what I get after applying the above.
[config_log_2.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10370880/config_log_2.txt)
[build_log_2.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10370881/build_log_2.txt)

**Comment by rsmarples** [comment]
I've added some more commits to the branch. It should now compile without any warnings.
Can you test it please?

**Comment by perkelix** [comment]
What I get after applying the 3 other patches:

[build_log_3.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10372741/build_log_3.txt)
[config_log_3.txt](https://github.com/NetworkConfiguration/dhcpcd/files/10372742/config_log_3.txt)

**Comment by rsmarples** [comment]
Great, all looks good now, thanks for testing.

**Comment by perkelix** [comment]
When compiling 9.4.1 on an earlier Debian release (GCC 10.2.1 and binutils 2.35.2), with the above 4 patches applied, I also get this warning:

ipv6nd.c: In function ‘ipv6nd_open’:
ipv6nd.c:230:3: warning: unsigned conversion from ‘int’ to ‘uint32_t’ {aka ‘unsigned int’} changes value from ‘-65’ to ‘4294967231’ [-Wsign-conversion]
  230 |   ICMP6_FILTER_SETPASS(ND_ROUTER_ADVERT, &filt);

**Comment by rsmarples** [comment]
So that means the earlier Debian release shipped with a buggy header as  ICMP6_FILTER_SETPASS and ND_ROUTER_ADVERT are defined by the system.

I went out of my way to clear if-linux.c of warnings from other system headers such as NLMSG and RTA macros when using clang, but I do have to draw the line somewhere.
