### ISSUE TITLE
Interface-specific commands not working with dhcpcd 9.4.1+

### ISSUE THREAD

**Issue by easybe** [NetworkConfiguration/dhcpcd#168]
In our Yoco Linux distribution (kernel 5.10), we would like to use dhcpcd 9.4.x ([recipe](https://github.com/openembedded/openembedded-core/tree/kirkstone/meta/recipes-connectivity/dhcpcd), "privsep" enabled).

However, even if we include all additional patches from the [dhcpcd-9](https://github.com/NetworkConfiguration/dhcpcd/tree/dhcpcd-9) branch, most notably https://github.com/NetworkConfiguration/dhcpcd/commit/a8ae8e7edfc231c7e39fd2444b84e120d8ae15d7 ("dhcpcd: Fix sending interface specific commands to manager process"), commands like `dhcpcd --release ...` or `dhcpcd --renew ...` do not work as expected. After executing the first command, any subsequent command will not have the desired effect. In the log we will see:

```
ps_ctl_dispatch: cannot handle another client
```

I suspect that the reason for `ps_control_client` not being set to `NULL` is the fact that `ps_ctl_sendeof` is not called as it is the case on `master` where we do not see the wrong behavior.

I tried porting over https://github.com/NetworkConfiguration/dhcpcd/commit/88d1590824689f47fc3e3ceff0bdaa7dad6a34f5 ("control: Fix working with new eloop") from `master` but did not succeed due to a segfault.

Any hints on how to fix this are highly appreciated.

Cheers,
Ezra.

**Comment by rsmarples** [comment]
Handling these commands has always been tricky.
I'm not sure it will be fixed in dhcpcd-9, but will stand a better chance of being resolved in dhcpcd-10

**Comment by easybe** [comment]
I did a quick test and the bug in questions seems to be fixed. In fact, I tested "master" back when I opened this issue and did not see the problem there. Thank you very much, we will be happy to upgrade to the new release and test it extensively.

**Comment by easybe** [comment]
Our automated tests look fine too.
