### ISSUE TITLE
DHCPv4 fails against Git

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#171]
9.4.1 plus cherry-picked Git commits built agaisnt Linux kernel 6.1.4 on Debian/testing.

Adding commits 96f055d2e48ce48ce828e1c4c175d05afcd1b299 to 7b74c4b2e4e8989e2c4f609bb3a7a6ff09660f51 resulted in broken DHCPv4 support. The only info provided by the log:

```
tammi 18 12:46:05 geode dhcpcd[465]: dhcpcd-9.4.1 starting
tammi 18 12:46:05 geode dhcpcd[468]: DUID < redacted>
tammi 18 12:46:07 geode dhcpcd[468]: enp0s13: IAID <redacted>
tammi 18 12:46:31 geode dhcpcd[468]: ps_ctl_listen: read: Success
```

That last line is what changed from previous releases. It wasn't there before. The process tree shows that privilege separation succeeded, but the daemon fails at DHCPv4 and /etc/resolv.conf only has the skeleton "written by dhcpcd" lines.

The exact same source built against Linux kernel 5.10 on Debian/stable produces usable binaries. We successfully solicit and get a lease i.e. the IAID line is followed by "soliciting a DHCP lease", offered IP, leased IP, etc. as expected.

**Comment by perkelix** [comment]
The key problem right now is that the sheer number of commits since 9.4.1 makes it very difficult to cherry-pick. We really need a 9.4.2 release, the sooner the better.

**Comment by rsmarples** [comment]
dhcpcd-9.5.0 released.
