### ISSUE TITLE
Stop work (killed, status=31/SYS) after upgrade

### ISSUE THREAD

**Issue by bmeirellesRJ** [NetworkConfiguration/dhcpcd#172]
Hi Roy,
After updating to the latest version, dhcp stopped working with the message:

syslog:
2023-01-18T10:31:23.936583-03:00 router dhcpcd[15146]: enp3s0: reading lease: /var/lib/dhcpcd/enp3s0.lease6
2023-01-18T10:31:23.936804-03:00 router dhcpcd[15146]: enp3s0: soliciting a DHCPv6 lease
2023-01-18T10:31:23.939934-03:00 router systemd[1]: dhcpcd.service: Main process exited, code=killed, status=31/SYS
2023-01-18T10:31:23.940795-03:00 router dhcpcd[15146]: ps_ctl_listen: read: Success
2023-01-18T10:31:23.941010-03:00 router dhcpcd[15146]: ps_ctl_recv: read: Success
2023-01-18T10:31:23.941755-03:00 router kernel: [ 5357.655111] audit: type=1326 audit(1674048683.932:17): auid=4294967295 uid=111 gid=65534 ses=4294967295 subj=unconfined pid=15145 comm="dhcpcd" exe="/usr/sbin/dhcpcd" sig=31 arch=c000003e syscall=318 compat=0 ip=0x7ffa29123045 code=0x0

systemd:
root@router:~# systemctl status  dhcpcd.service
● dhcpcd.service - DHCP Client Daemon on all interfaces
     Loaded: loaded (/lib/systemd/system/dhcpcd.service; enabled; preset: enabled)
     Active: deactivating (stop-sigterm) (Result: signal) since Wed 2023-01-18 10:31:23 -03; 5s ago
       Docs: man:dhcpcd(8)
    Process: 15143 ExecStart=/usr/sbin/dhcpcd -q -b (code=exited, status=0/SUCCESS)
   Main PID: 15145 (code=killed, signal=SYS)
      Tasks: 2 (limit: 9291)
     Memory: 672.0K
        CPU: 108ms
     CGroup: /system.slice/dhcpcd.service
             ├─15146 "dhcpcd: [privileged proxy]"
             └─15147 "dhcpcd: [network proxy]"

jan 18 10:31:23 router dhcpcd[15146]: enp1s0: waiting for carrier
jan 18 10:31:23 router dhcpcd[15146]: enp2s0: waiting for carrier
jan 18 10:31:23 router dhcpcd[15146]: enp3s0: IAID 31:14:9e:77
jan 18 10:31:23 router dhcpcd[15146]: enp3s0: IA type 3 IAID 00:00:00:00
jan 18 10:31:23 router dhcpcd[15146]: enp3s0: IA type 25 IAID 00:00:00:00
jan 18 10:31:23 router dhcpcd[15146]: enp3s0: reading lease: /var/lib/dhcpcd/enp3s0.lease6
jan 18 10:31:23 router dhcpcd[15146]: enp3s0: soliciting a DHCPv6 lease
jan 18 10:31:23 router systemd[1]: dhcpcd.service: Main process exited, code=killed, status=31/SYS
jan 18 10:31:23 router dhcpcd[15146]: ps_ctl_listen: read: Success
jan 18 10:31:23 router dhcpcd[15146]: ps_ctl_recv: read: Success

I tested some systemd unit settings on this page suggested by Martin Eric  maintainer of this package on debian  but it didn't work.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020641

 My current systemd:

 /etc/systemd//system/multi-user.target.wants/dhcpcd.service
  
[Unit]
Description=DHCP Client Daemon on all interfaces
Wants=network.target
Before=network.target
Documentation=man:dhcpcd(8)

[Service]
Type=forking
PIDFile=/run/dhcpcd/pid
ExecStart=/usr/sbin/dhcpcd -q -b
ExecStop=/usr/sbin/dhcpcd -x
RuntimeDirectory=dhcpcd

[Install]
WantedBy=multi-user.target

I'm using debian bookworm with the updated packages
Linux router 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09

Can you help me? Thank you very much

**Comment by rsmarples** [comment]
You've not actually said which dhcpcd version you're using!
Anyway, this should already be fixed in the dhcpcd-9 branch - can you test it please?

**Comment by bmeirellesRJ** [comment]
Hi, Roy

i'm using 9.4.1-13. debian sid package

How to install the latest version on debian?

thank you very much

**Comment by rsmarples** [comment]
```
git clone https://github.com/NetworkConfiguration/dhcpcd.git
cd dhcpcd
git checkout dhcpcd-9
./configure
make
src/dhcpcd -x
src/dhcpcd -dB
```

You then have the latest dhcpcd-9 running in the terminal with debug active.
If that works fine you can then run `make proginstall` to install it - although some things will be in different places due to how Debian installs dhcpcd.

**Comment by rsmarples** [comment]
You'll need to adjust the service as it installs by default to /sbin and you have /usr/sbin/dhcpcd I've just noticed.

**Comment by bmeirellesRJ** [comment]
Hi Roy,

It worked. I didn't need to change anything from the systemd unit above

Thank you very much! hug!

**Comment by rsmarples** [comment]
dhcpcd-9.5.0 is now released.
