### ISSUE TITLE
logic bug with setting autoconf?

### ISSUE THREAD

**Issue by agowa** [NetworkConfiguration/dhcpcd#176]
I'm a little bit confused by this code:
https://github.com/NetworkConfiguration/dhcpcd/blob/4c97eb896bbb9a2b285efce2fa15aa9d2a9492d1/src/if-linux.c#L2142-L2143

According to the kernel documentation autoconf is a boolean, so it is either 0 or 1 (or in our case -1 if it doesn't exist).

Why do we check `ra != 1 && ra != -1` I. E. `ra == 0` but then only ever set it to 0 in the next line? Either the 2nd line should set it to 1 or the first line should check if `ra == 1`.

Is this a bug or am I just reading this wrong?

**Comment by perkelix** [comment]
Are we talking about RA reception? If yes, the options are 0 (disabled), 1 (enabled) or 2 (enabled and forward packets).

**Comment by rsmarples** [comment]
Yes. It's a tri-state value, but for the purposes of saying "is the kernel doing ra or not" it's a boolean.
We now just test the error state and then non zero state and make it zero if not an error.
