### ISSUE TITLE
privsep fails in musl

### ISSUE THREAD

**Issue by catdevnull** [NetworkConfiguration/dhcpcd#186]
I'm not sure what's the exact issue but it seems it's a musl compatibility problem. https://gitlab.alpinelinux.org/alpine/aports/-/issues/14620

**Comment by rsmarples** [comment]
Based on the diagnostic we need to allow the madvise syscall.

**Comment by rsmarples** [comment]
@catdevnull can you test that patch please? I don't have a recent enough VM to replicate but it should work or progress.

**Comment by catdevnull** [comment]
![image](https://user-images.githubusercontent.com/86896666/220986245-f0dedaab-bb72-4668-8cf6-0eb345c0e6d1.png)

It don't look to good (Alpine 3.17.0, a little outdated though)

**Comment by rsmarples** [comment]
Is another syscall failing in your dmesg?

**Comment by catdevnull** [comment]
![image](https://user-images.githubusercontent.com/86896666/221024703-3ca5e2f8-ede0-4da1-984c-5e68bb52d9cd.png)

**Comment by rsmarples** [comment]
That's the socket syscall? Might as well disable privsep before I enable that. In away for a long weekend, but I'll try and look into it when I'm back.

**Comment by rsmarples** [comment]
OK, there are enough fixes on this branch now so it works fine on the Alpine-3.17.2-x86_64.
You might have to kill any existing dhcpcd instances as it wasn't handling control errors properly and may hang around.
Let me know!

**Comment by catdevnull** [comment]
![image](https://user-images.githubusercontent.com/86896666/222005648-a768ff97-f8ba-4578-8a37-b77342988cd2.png)


![image](https://user-images.githubusercontent.com/86896666/222005756-2728364d-730d-4e34-8112-f50d78de4e74.png)
