### ISSUE TITLE
Add command line option -T to usage()

### ISSUE THREAD

**Issue by SpareSimian** [NetworkConfiguration/dhcpcd#189]
Update the usage() function to add the -T option to dump the environment variables for hooks to the log. See also issue #3.

**Comment by rsmarples** [comment]
```
$ dhcpcd --help
usage: dhcpcd   [-146ABbDdEGgHJKLMNPpqTV]
```

Yup, T is already there.

**Comment by SpareSimian** [comment]
What's missing is the detail: "[-T, --test]".

**Comment by rsmarples** [comment]
Only the options that take a parameter are expanded to inlcude the GNU long option in usage and the man page.
