### ISSUE TITLE
IFA_ADDRESS and IFA_LOCAL confusion for dhcpv6 over ppp?

### ISSUE THREAD

**Issue by jon-y** [NetworkConfiguration/dhcpcd#201]
I am using dhcpv6 over PPP (yes my ISP is weird), I am on Gentoo Linux, and this issue is only happening with dhcp-10.x, the older 9.4.1 and 9.5.0 were fine where I am able to get an IPv6 address normally over ppp.

_if_addrflags6 seems to complain about ppp ipv6 addresses, causing the following message:
if_learnaddrs: if_addrflags6: fe80::XXXX%ppp0: No such process

I do not get any ipv6 addresses from my ISP after that.

If I acquire the ipv6 address with dhcpcd-9, and rerun dhcpcd-10 with a dummy IFA_LOCAL in the case/switch in _if_addrflags6, it don't seem to fix the issue, causing a different message to be emitted:
if_learnaddrs: if_addrflags6: 2001:XXXX%ppp0: No such process

Possibly related to the change in 064767e3610b7f8df974592f340dbbf45f8e44ca.

For the record, ip a output is:
```
6: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1460 qdisc pfifo_fast state UNKNOWN group default qlen 3
    link/ppp 
    inet 202.XXX.XXX.XXX.XXX peer 202.XXX.XXX.XXX/32 scope global ppp0
       valid_lft forever preferred_lft forever
    inet6 2001:XXXXX/128 scope global dynamic noprefixroute 
       valid_lft 259199sec preferred_lft 172799sec
    inet6 fe80::XXXXX peer fe80::XXXXX/128 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by rsmarples** [comment]
@jon-y thanks for the heads up about ifa confusion with ppp interfaces. The above commit should fix - can you test it please? I don't have any PPP interfaces here that I can replicate with atm.

**Comment by rsmarples** [comment]
OK, This new patch should fix it! I finally got around to testing it.
Can you verify it works please?

**Comment by jon-y** [comment]
Looks good so far, it is able to acquire an ipv6 address. Thanks for the fix, I'll continue monitoring and see if I notice any weird behaviors,
