### ISSUE TITLE
(Option for) disable bringing up interfaces automatically. 

### ISSUE THREAD

**Issue by kjonca** [NetworkConfiguration/dhcpcd#207]
I have debian box, and I try to migrate from isc-dhcp-client to dhcpcd (especially my scripts) I found migration pretty straighforward, but I found one thing. When I connect new interface (for example usb ethernet card) dhcpcd try to bring it up and configure it immediately, which in turn can change routes. It would be nice to have chance keep these interfaces down, and only  manually "ip link set up dev et0"  cause dhcpcd try to get dhcp leases.

**Comment by rsmarples** [comment]
`man dhcpcd.conf(5)` will describe the `noup` option which suits your needs

```
# Don't bring up any interfaces by default
noup

# OR don't bring up specific interface only
interface eth0
    noup
```

**Comment by kjonca** [comment]
Oh. shame on me, as I overlooked it.
Although this not fully compatible with debian's ifupdown package.
when I have in  /etc/network/interfaces
`iface usb0 inet dhcp`

and try to 
ifup usb0
I got in logs:

```
2023-05-17T16:45:24.537183+02:00 dorsz dhcpcd[166540]: ps_ctl_dispatch: cannot handle another client
2023-05-17T16:45:24.537229+02:00 dorsz dhcpcd[166540]: control_free: No such file or directory

```
and interface is still down.

Am I able to resolve this or should discuss with debian folks?

**Comment by kjonca** [comment]
Thank you for comprehensive information. I still need to deal with routing metrics, but this is rather my  side. Thank you again.
