### ISSUE TITLE
Segfault in ps_root_unlink

### ISSUE THREAD

**Issue by cdown** [NetworkConfiguration/dhcpcd#210]
Hey! I have no idea how to repro this, but one of my servers dropped off the net in the night and I noticed that it's because dhcpcd had crashed:

```

chuanr % q coredumpctl info
           PID: 332 (dhcpcd)
           UID: 973 (dhcpcd)
           GID: 973 (dhcpcd)
        Signal: 11 (SEGV)
     Timestamp: Fri 2023-06-02 12:17:39 EDT (23h ago)
  Command Line: $'dhcpcd: [manager] [ip4] [ip6]'
    Executable: /usr/bin/dhcpcd
 Control Group: /system.slice/dhcpcd.service
          Unit: dhcpcd.service
         Slice: system.slice
       Boot ID: eaed780cc26c423c9a49669be3c7dac7
    Machine ID: a1475fd543e4465082ceb6bec117f2eb
      Hostname: chuanr
       Storage: /var/lib/systemd/coredump/core.dhcpcd.973.eaed780cc26c423c9a49669be3c7dac7.332.1685722659000000.zst (present)
  Size on Disk: 41.1K
       Message: Process 332 (dhcpcd) of user 973 dumped core.
                
                Stack trace of thread 332:
                #0  0x00005582d38afc03 ps_root_unlink (dhcpcd + 0x3fc03)
                #1  0x00005582d38800b8 control_stop (dhcpcd + 0x100b8)
                #2  0x00005582d387a9a2 main (dhcpcd + 0xa9a2)
                #3  0x00007fa171311850 n/a (libc.so.6 + 0x23850)
                #4  0x00007fa17131190a __libc_start_main (libc.so.6 + 0x2390a)
                #5  0x00005582d387bc35 _start (dhcpcd + 0xbc35)
                ELF object binary architecture: AMD x86-64
chuanr % dmesg | grep -A1 dhcpcd
[Fri Jun  2 12:17:39 2023] dhcpcd[332]: segfault at 38 ip 00005582d38afc03 sp 00007fff47488770 error 4 in dhcpcd[5582d387a000+43000] likely on CPU 0 (core 0, socket 0)
[Fri Jun  2 12:17:39 2023] Code: ff 15 61 20 02 00 66 0f ef c0 48 89 e1 48 89 df 48 8b 93 a8 03 00 00 48 83 c0 01 48 89 6c 24 40 48 89 44 24 48 48 8d 44 24 40 <8b> 72 38 ba 13 00 00 00 0f 29 44 24 50 48 c7 44 24 30 00 00 00 00
```

I don't have much debugging information, unfortunately. There is nothing recently logged by dhcpcd before this happening. 

Version information:

```
chuanr % uname -a         
Linux chuanr 6.1.31-1-lts #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 14:36:16 +0000 x86_64 GNU/Linux
chuanr % pacman -Q dhcpcd 
dhcpcd 10.0.1-1
```

**Comment by rsmarples** [comment]
Has privsdep been disabled? `dhcpcd --version`

**Comment by cdown** [comment]
Looks like it's compiled in:

```
% dhcpcd --version
dhcpcd 10.0.1
Copyright (c) 2006-2023 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH PRIVSEP
```

**Comment by rsmarples** [comment]
Well, if the stack trace is to be believed, dhcpcd crashed when it was shutting down. We know this because `control_stop` is only called then. I'm guessing you can't easily reproduce this either.

**Comment by rsmarples** [comment]
Every 5 days? Could you test the patch in 8b29c0ddf026c1c5647c3b8c6cfe21699c4056ae please?

**Comment by zacknewman** [comment]
> Every 5 days? Could you test the patch in [8b29c0d](https://github.com/NetworkConfiguration/dhcpcd/commit/8b29c0ddf026c1c5647c3b8c6cfe21699c4056ae) please?

To expand on this, the issue I had was a script kiddie sending traffic on a 5-day interval; so the 5-day part is not as important as the consistent nature of the interval. Additionally, `dhcpcd` never caused a segmentation fault but instead gracefully exited when a 0-byte packet was sent to UDP port 68. If you are not using `dhcpcd` for DHCP, then `master` will likely not solve your problem.

I was able to detect the issue by running `tcpdump -ntt -i <outgoing_interface> -w pkts.dat '(udp and ((ip and (dst port 67 or dst port 68)) or (ip6 and (dst port 546 or dst port 547)))) or (ip6 and icmp6) or (ip and icmp)' &` which may help you detect the problematic packet if there is one.

**Comment by lhooge** [comment]
Thanks great. I've read your issue and I'm able to reproduce it: 

```
#!/bin/python
import socket
addr = 'XX.XX.XX.XX'  
socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0).sendto(b'', (addr, 68))
```

But with the patched version I do not get a segfault anymore. So the patch works!

With the patched version I can see in the logs:
Jun 16 18:57:28 hoogi dhcpcd[20138]: ens3: truncated packet (0) from xxxxxxx
Jun 16 18:57:28 hoogi dhcpcd[20138]: ens3: truncated packet (0) from xxxxxxx

**Comment by zacknewman** [comment]
> It is really confusing for me, that I'm not able to reproduce this on 9.4.1 and you did not get a segfault. The arch maintainers changed a bit [1]. But privsep was activated before and I can't see anything preventing a segfault here on 9.4.1.

Hm, that is a little bizarre. I am running OpenBSD 7.3 and before that OpenBSD 7.2 and OpenBSD 7.1. All three of them had `dhcpcd 9.4.1` with privsep, and all three were having exits every 5 days. While I didn't detect the truncated packet problem until OpenBSD 7.3, it seems highly unlikely that was not always causing the issue the ≈ 1.5 years I was experiencing exits.

You are using Linux, and there were other changes between `9.4.1` and `master` including changes to the privsep code. I have a feeling the privsep code has always been more mature on the *BSDs than with Linux—Roy would have to confirm/deny that—so it is not unfathomable that the privsep changes between `9.4.1` and `master` were more drastic on Linux which among other things introduced the bug OpenBSD had been afflicted by for a while.

I take partial responsibility for that since instead of actually solving the problem all this time I lazily and hackily "solved" the problem by using a ksh script that would start up `dhcpcd` any time it was down. Had I actually tried to solve the problem, then perhaps you and others would have never been hit with this issue.

**Comment by rsmarples** [comment]
> I have a feeling the privsep code has always been more mature on the *BSDs than with Linux—Roy would have to confirm/deny that—so it is not unfathomable that the privsep changes between `9.4.1` and `master` were more drastic on Linux which among other things introduced the bug OpenBSD had been afflicted by for a while.

Not really.
OpenBSD was the easiest.
FreeBSD was the hardest.
Linux is just nuts for maintainers due to glibc changing what kernel calls it makes.

FWIW I think FreeBSD has the best implementation.

**Comment by rsmarples** [comment]
I don't have much time for dhcpcd right now, but I do have an idea about what the issue is with this bug - which does likely need fixing.

**Comment by zacknewman** [comment]
> Not really. OpenBSD was the easiest. FreeBSD was the hardest. Linux is just nuts for maintainers due to glibc changing what kernel calls it makes.
> 
> FWIW I think FreeBSD has the best implementation.

I have read several of your posts on your website including the two on Capsicum vs. Pledge which indicated neither was necessary better than the other; and while both are good, they each have things they could improve upon.

Obviously those posts are three years old now, and things have likely changed.

**Comment by rsmarples** [comment]
So the new process exit detection code in dhcpcd is working just fine, and we now trip up badly if it's the root process that exits unexpectedly! Hopefully this simple but largeish change will stop things from crashing more than otherwise.
