### ISSUE TITLE
How to re-initiate auto IP on rebind if already in auto IP

### ISSUE THREAD

**Issue by mahendra-msp** [NetworkConfiguration/dhcpcd#220]
Hi,

We are using 8.6.1 version of Dhcpcd. If our device is already in autoip ( with no DHCP server in the network ), when we do rebind, it does not re-initiate autoip sequence. Due to this, we do not see any ARP packet in the network.

Could you please let me know how to re-initialize or force dhcpcd to re-init auto IP sequence ?
Please let me know your response as it is a critical issue for us.

Thnaks
Mahendra

**Comment by rsmarples** [comment]
dhcpcd-8 is very much unsupported.
dhcpcd-9 is only getting security updates.
dhcpcd-10 works with my testing - issuing `dhcpcd -n` causes the autoip to rebind with my testing.

**Comment by mahendra-msp** [comment]
Hi Roy Marples, 

Thank you for the quick response. Much appreciate it.
Although we are in 8.6.1 version, we can not move immediately to latest version.  

I understand that "dhcpcd -n" is same as "dhcpcd --rebind" and we are already calling rebind. Looks like for autoip case, there is an issue in older versions. Can you please provide info on commit details where the fix was done ? This will help me to refer to it and try to apply the same as patch on 8.6.1

Thank you
Mahendra

**Comment by rsmarples** [comment]
Any fix is likely in src/dhcpcd.c, but it has changed a fair bit since v8 due to sandboxing so any fixes of late just won't apply.

Is there any reason why you cannot move? Generally it's just a drop in upgrade.
