### ISSUE TITLE
do not delegate IPv6 PD is there is no IPv6 Routers available

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#221]
10.0.1 (reproducible on earlier too).

In its current form, dhcpcd will happily delegate an IPv6 prefix even when the ISP replied with;

Jul 05 08:22:43 p8h61 dhcpcd[5241]: enp4s0: no IPv6 Routers available

If no IPv6 router is available, dhcpcd should abort PD, since there is no sense in delegating an unroutable prefix.

**Comment by rsmarples** [comment]
Why would the delegated prefix not be routable? It's routable by it's very definition.

**Comment by perkelix** [comment]
Because if RA reports no available router, 'ip -6 r' correspondingly shows that there is no default route i.e. IPv6 is not routable.

**Comment by rsmarples** [comment]
No, that means there is no default route or router.
IPv6 is perfectly routable inside the delegated prefix.

What do you imagine happens if the router is available, you get your prefix and then the router goes offline?
How is this any different? What is the actual problem you are attempting to solve?

**Comment by perkelix** [comment]
If there is no default route, connecting to the outside world via IPv6 does fail.

**Comment by rsmarples** [comment]
Yes it does. What does that have to do with prefix delegation? As I said earlier IPv6 works fine within the prefix.
You could even get a RA which says it's not a router but also provides some on-link prefixes.
What is your expectation of what would happen here?

This is no different from a DHCPv4 server giving you a 192.168.x.x address but no default router. You can still communicate with the hosts inside the 192.168.x.x subnet.
