### ISSUE TITLE
dhcpcd 10.0.2 broke Wi-Fi Roaming 

### ISSUE THREAD

**Issue by borkra** [NetworkConfiguration/dhcpcd#228]
Commit [4f5c4999b690a0a95bcbf0c1bb5c12dd3618308f](https://github.com/NetworkConfiguration/dhcpcd/commit/4f5c4999b690a0a95bcbf0c1bb5c12dd3618308f)
broke Wi-Fi roaming handling.

If IFF_DORMANT is set Wi-FI is in the middle of roaming from AP to another and UP state should not be dropped and routes should not be cleared, to allow seamless operation during roaming without dropping all network connections.

**Comment by rsmarples** [comment]
Can you test the above patch please? I don't have any mechanism to test this .... :(

**Comment by perkelix** [comment]
ping @borkra

**Comment by borkra** [comment]
I have no ability to test this at this time.

**Comment by borkra** [comment]
We retested this and original code works and  new one not
