### ISSUE TITLE
IPv4 lease and IPv6 LFT values assigned backwards

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#240]
I use dhcpcd (10.0.2) to lease IPv4 for my NAT router and delegate IPv6 to my LAN.

For some reason, dhcpcd assigns the IPv6 LFT values it received to the WAN interface's v4 address and the DHCPv4 lease time it received to the LAN interface's v6 address. 

```
2: enp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 87.94.149.210/19 brd 87.94.159.255 scope global dynamic noprefixroute enp4s0
       valid_lft 3139sec preferred_lft 2419sec
    inet6 fe80::4563:25d2:2d2f:89f/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
5: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.1/16 brd 172.16.255.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 2001:14ba:a028:f205::1/64 scope global dynamic noprefixroute 
       valid_lft 3137sec preferred_lft 3137sec
    inet6 fe80::1c00:4f53:656b:c78b/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```
This should obviously be the other way around i.e. DHCPv4 lease to the WAN interface with the same valid and preferred IPv4 values, and LAN interface with different valid/preferred IPv6 values.

Relevant log lines:
```
Aug 16 20:12:34 p8h61 dhcpcd[993]: enp4s0: REPLY6 received from fe80::bb
Aug 16 20:12:34 p8h61 dhcpcd[993]: enp4s0: renew in 1800, rebind in 2880, expire in 3600 seconds
[...]
Aug 16 20:12:37 p8h61 dhcpcd[993]: enp4s0: leased 87.94.149.210 for 3600 seconds
```

Given the above, the WAN interface (enp4s0) should get an IPv4 lease for 3600 seconds (shown with valid and preferred LFT at the same value), while the LAN interface should get a delegated IPv6 prefix with a valid_lft of 3600 seconds and preferred_lft of 2880 seconds.

**Comment by rsmarples** [comment]
I'm not sure there is a bug here.
For DHCPv4, although there is no valid or preferred time, we can work these out from T2 and lease expiry.
For DHCPv6 the T1 and T2 timers have no bearing on the valid or preferred times. You should enable dhcpcd debug to see the timings that dhcpcd assigns to the address when it adds it.

**Comment by perkelix** [comment]
The bug is obvious. The values assigned are backwards. Debug is enabled. What should I look for?

**Comment by rsmarples** [comment]
The bug is not obvious to me. What you posted could be correct.
Certainly DHCPv6 doesn't leak into DHCP for timings on addresses (or vice versa).

Well, post the output of `dhcpcd -U`
I should probably add the T1 and T2 timers to the DHCP environment as well.
As we can't see them, a tcpdump of the DHCP operation or just attach the dhcpcd lease file so we can look at it.

**Comment by perkelix** [comment]
```
send OK
reason=CARRIER
interface=enp4s0
protocol=link
if_configured=true
ifcarrier=up
ifmetric=1002
ifwireless=0
ifflags=69699
ifmtu=1500

reason=RENEW
interface=enp4s0
protocol=dhcp
ip_address=87.92.246.88
subnet_cidr=17
broadcast_address=87.92.255.255
network_number=87.92.128.0
subnet_mask=255.255.128.0
routers=87.92.128.1
domain_name_servers=62.241.198.245 62.241.198.246
dhcp_lease_time=3600
dhcp_message_type=5
dhcp_server_identifier=62.241.198.74
dhcp_renewal_time=1800
dhcp_rebinding_time=2880
vendor_class_identifier=dhcpcd-10.0.2:Linux-6.1.0-11-amd64:x86_64:GenuineIntel

reason=ROUTERADVERT
interface=enp4s0
protocol=ra
nd1_from=fe80::bb
nd1_acquired=32620
nd1_now=33691
nd1_hoplimit=64
nd1_flags=M
nd1_lifetime=4500
nd1_source_address=00005e000101

reason=RENEW6
interface=enp4s0
protocol=dhcp6
dhcp6_server_id=00030001405582a423d8
dhcp6_client_id=000100012bcc678ec86000d0734d
dhcp6_ia_pd1_iaid=00000000
dhcp6_ia_pd1_t1=1800
dhcp6_ia_pd1_t2=2880
dhcp6_ia_pd1_prefix1_pltime=3600
dhcp6_ia_pd1_prefix1_vltime=3600
dhcp6_ia_pd1_prefix1_length=56
dhcp6_ia_pd1_prefix1=2001:14ba:a04c:3600::
dhcp6_name_servers=2001:14b8:1000::1 2001:14b8:1000::2

```

**Comment by rsmarples** [comment]
```
Aug 16 20:12:37 p8h61 dhcpcd[993]: enp4s0: leased 87.94.149.210 for 3600 seconds

dhcp_rebinding_time=2880

dhcp6_ia_pd1_prefix1_pltime=3600
dhcp6_ia_pd1_prefix1_vltime=3600
```

This seems to match your addresses? I don't see any issue with dhcpcd here.

**Comment by perkelix** [comment]
Valid and preferred IP6 times should be different.

Valid and preferred IPv4 times should be the same, since IPv4 has no notion of preferred or valid, it only has a lease time.

**Comment by rsmarples** [comment]
But they are not different. Why not look at the transaction using a 3rd party tool such as wireshark or tcpdump? You will see that pltime and vltime are the same (remember, they have no relation to the t1, t2 timers for the lease which *are* different).

As I said earlier, for DHCPv4 we can set the vltime to the lease time and pltime to rebind time as they are pretty much equivalent. renew time is the shortest and does not factor into address times on Linux.

**Comment by perkelix** [comment]
They are the same for DHCPv4. The key problem is IPv6. It makes no sense for valid/preferred to have the same value.

**Comment by rsmarples** [comment]
So fix the DHCPv6 server to send a different pltime to vltime? dhcpcd is just doing what it's told.
Having vltime and pltime the same is within the spec and perfectly valid.
