### ISSUE TITLE
core dump on inet6_getroutes

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#247]
10.0.2 segfaulted today upon the host resuming from hibernate. Traces attached.

The logs suggest that dhcpcd correctly noticed that, upon de-hibernating, it was no longer on the same IPv6 prefix, deleted  prefix::1, but somehow failed at setting a new one. I had to forcefully restart dhcpcd to set prefix::1 and, even then, it initially would not exit.

[coredumpctl_debug_577981_dhcpcd.txt](https://github.com/NetworkConfiguration/dhcpcd/files/12710572/coredumpctl_debug_577981_dhcpcd.txt)
[coredumpctl_debug_578681_dhcpcd.txt](https://github.com/NetworkConfiguration/dhcpcd/files/12710574/coredumpctl_debug_578681_dhcpcd.txt)
[syslog_dhcpcd.txt](https://github.com/NetworkConfiguration/dhcpcd/files/12710620/syslog_dhcpcd.txt)

**Comment by rsmarples** [comment]
I notice that each crash dhcpcd received SIGTERM 3 times each.
That's not normal - dhcpcd should exit on SIGTERM and not process another.

I'll see if I can setup a test case to simulate that.

**Comment by rsmarples** [comment]
Both crash dumps, dhcpcd was trying to exit as a result of a signal as they have dhcpcd_signal_cb in the stack trace for each.
I see nothing here for hibernation - all dhcpcd should get here is a carrier down/up message to indicate possible network change.

**Comment by perkelix** [comment]
The system log indeed starts with dhcpcd losing the carrier, deleting routes as a result. Then it finds the carrier again, gets an IPv4 address and an IPv6 prefix, but fails at restoring the default route for that prefix.

**Comment by rsmarples** [comment]
```
Sep 24 17:03:39 p8h61 dhcpcd[1013]: br0: carrier lost
```

br0 does not gain carrier according to dhcpcd, so I'm guessing that your complaint is that the delegated prefix is not added to br0 when you resume from hibernation?

**Comment by perkelix** [comment]
Precisely. the prefix and default route are removed upon detecting the loss of carrier, but not added back once a new prefix has been acquired.

**Comment by rsmarples** [comment]
So we have two issues. I think the main issue of dhcpcd crashing on many signals has been fixed.
The second issue is the carrier state of br0.

When your system comes out of hibernation and doesn't get a prefix, what is the output of `ip a`

**Comment by perkelix** [comment]
It shows br0 lacking any external v6 address. It only has v6 link-local.

Btw, the crash trace does mention in the summarry that core dumped at inet6_getroutes. This does match the lack of prefix.

**Comment by rsmarples** [comment]
I'm more interested in the interface flags br0 has, such as `<BROADCAST,MULTICAST,UP,LOWER_UP>` which is why I asked for the output of the command :)

**Comment by perkelix** [comment]
This is what it shows upon returning from hibernate:
```
5: br0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether <redacted> brd ff:ff:ff:ff:ff:ff
    inet 172.16.1.1/16 brd 172.16.255.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::2f55:43cd:7ddd:464d/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

**Comment by rsmarples** [comment]
So clearly the bridge does not have a carrier. dhcpcd will only delegate to the interface when it gains carrier so you need to find a way to bring the carrier up for br0.

**Comment by rsmarples** [comment]
`alllowinterfaces` should only include br0 if we expect DHCP or DHCPv6 or RA to work on the interface.
As we are only delegating to br0 then it doesn't need to be included.

That being said, this won't affect the carrier state reported by the kernel. All dhcpcd can do is bring an interface up when it first starts and the bridge is indeed up.

Can you please add `debug` to the top level of dhcpcd.conf and restest? You should see `br0: has no carrier, cannot delegate addresses` If so maybe I should change the loglevel of that message to warning.
