### ISSUE TITLE
dhcpcd-10.0.5 without privsep no longer forks into background

### ISSUE THREAD

**Issue by Polynomial-C** [NetworkConfiguration/dhcpcd#262]
This happens on a Gentoo system with netifrc but can easily be reproduced without:

* run something like `dhcpcd -A eth0`
* watch `pidof dhcpcd` returning nothing
* Wait till _max-lease-time_ kicks in and see your system no longer having a configured network device.

Bisecting the issue revealed commit c32c88b642b8c65eb68b505e0783fd46b57fc6fa to be blamed here. Reverting that commit for 10.0.5 release "fixes" this issue.

**Comment by Polynomial-C** [comment]
I've done more tests and this issue only appears when dhcpcd has been built without privsep support.

**Comment by rsmarples** [comment]
@Polynomial-C can you test the `fix_no_privsep` branch please? I can't reproduce your exact issue but I did make a few fixes for non privsep builds.

**Comment by Polynomial-C** [comment]
@rsmarples Unfortunately, the two commits from `fix_no_privsep` don't help. dhcpcd configures the interface and then exits with no background fork.

**Comment by rsmarples** [comment]
I cannot reproduce that. Is dhcpcd crashing somehow maybe that we are not seeing? I'll try and spin up a Gentoo VM next week, but I don't really have much free time.

**Comment by Polynomial-C** [comment]
Running `dhcpcd -B -d -A eth0` shows no crashes. The process keeps running till I press `CTRL+C`. 
When calling without `-B` I don't see anything unusual except that the last line `forked to background` is missing.

**Comment by rsmarples** [comment]
I have reproduced the the issue and am looking working on a fix.

**Comment by rsmarples** [comment]
@Polynomial-C  should be good now, please test.

**Comment by Polynomial-C** [comment]
@rsmarples: I can confirm. It's fixed now. Thank you very much!

**Comment by rsmarples** [comment]
@Polynomial-C Excellent! I've pushed a few more fixes for various OS's so we should be good now.... feel free to re-test ;)

**Comment by peabee** [comment]
May be related..... I think the -b switch causes problems with dhcpcd-10.0.5
Not extensively tested but I have code (not mine) which includes the -b switch which worked fine with 10.0.4 and doesn't work with 10.0.5 (Slackware Current builds) but starts to work again if the -b switch is removed.
Should I report anywhere else?

**Comment by pierre-labastie** [comment]
Using [BLFS](https://www.linuxfromscratch.org/blfs), I get "dhcpcd_fork_cb: Connection reset by peer", but I think it is the same issue, because it is fixed by the new commits. This issue is rather annoying. Can we expect another release soon?

**Comment by rsmarples** [comment]
I'm awaiting on feedback from two issues and I'll make a new release.
