### ISSUE TITLE
DHCPCD doesn't clean up addresses/routes/dns on shutdown

### ISSUE THREAD

**Issue by cfra** [NetworkConfiguration/dhcpcd#263]
Sorry if this has been reported before, but I have not found it with a brief search.

I have been using dhcpcd for some time and in the past, it behaved in the way that it removed addresses, routes and dns entries when it was terminated.

Now, when terminate dhcpcd using something like `dhcpcd -x wlan0`, dhcpcd exits, but the address, routes and dns info and everything stay around.

This is not really what I want. When I terminate dhcpcd, I want it to relase all the resources and to remove any configuration that was done by it, like it used to do in the past (that even worked when blatantly running `sudo killall dhcpcd`).

Is there a way to configure this, or should I shut it down in a different way these days? :thinking:

**Comment by rsmarples** [comment]
Use `-k` to exit, not `-x`.
You  could also remove the `persistent` command from `/etc/dhcpcd.conf`.
