### ISSUE TITLE
dhcpcd -x or -k has no effect

### ISSUE THREAD

**Issue by pierre-labastie** [NetworkConfiguration/dhcpcd#264]
version: dhcpcd current master (commit 6788608)
configured with:
```
./configure --prefix=/usr                \
            --sysconfdir=/etc            \
            --libexecdir=/usr/lib/dhcpcd \
            --dbdir=/var/lib/dhcpcd      \
            --runstatedir=/run           \
            --disable-privsep
```
then `make` and `make install` (using default dhcpcd.conf)

dhcpcd started with `dhcpcd -b -q -4 eth0`
then `ps aux | grep dhcp` shows:
```
root       563  0.0  0.0   8740  2704  ?           S    15:27    0:00 dhcpcd: eth0 [ip4]
pierre     624  0.0  0.0  29492  2304  tty1        S+   15:27    0:00 grep dhcp
```

Observed behavior:
when running `sudo dhcpcd -x eth0` or `sudo dhcpcd -k eth0`, there is message:
```
dhcpcd is not running
```
and `ps aux | grep dhcp` shows:
```
root       563  0.0  0.0   8740  2704  ?           S    15:27    0:00 dhcpcd: eth0 [ip4]
pierre     629  0.0  0.0  29492  2304  tty1        S+   15:30    0:00 grep dhcp
```

Expected behavior:
after running either of the command , there should be no error message, and `ps aux | grep dhcp` should only show the "grep" line

**Comment by pierre-labastie** [comment]
Note that I haven't tested with 10.0.5, since it is broken with --disable-privsep, and dhcpcd is unable to background itself

**Comment by perkelix** [comment]
> It turns out that the pid file when passing -4 is created as `/run/dhcpcd/eth0-4.pid`, but **dhcpcd -k eth0** wants to get the pid from `/run/dhcpcd/eth0.pid`, which does not exist.
> 
> Running **dhcpcd -k -4 eth0** works as expected.
> 
> But it was not clear to me that **-4** needed to be passed for stopping dhcpcd when it was started with **-4**. At least I cannot see anything in the documentation telling this.

These definitely need to be documented.

**Comment by rsmarples** [comment]
Does this clear it up?

**Comment by pierre-labastie** [comment]
> Does this clear it up?

Yeah thanks. Just bump the year in date :)
