### ISSUE TITLE
global noipv6 causes errors when privsep is enabled

### ISSUE THREAD

**Issue by hpresnall** [NetworkConfiguration/dhcpcd#267]
Privilege separation appears to be broken in Alpine linux. I am seeing multiple outputs of `ps_root_recvmsg: Bad file descriptor` trying to use dhcpcd 10.0.2-r1 on Alpine linux 3.18 or 10.0.5-r0 from 3.19.

Backing down to dhcpcd-9.4.1-r3 from 3.17 fixes the issues with no other changes to packages or config. Pulling latest and building with `--disable-privsep` also fixes the issue.

Seems like it's an ipv6 issue because I do get an ipv4 address. But, dhcp6 and slaac fail.

Config file is 

    duid
    controlgroup dhcpcd
    vendorclassid
    require dhcp_server_identifier
    option domain_name_servers, domain_name, domain_search
    option classless_static_routes
    option interface_mtu
    option rapid_commit
    slaac private temporary
    noipv4
    noipv4ll
    noipv6
    allowinterfaces eth0
    interface eth0
      ipv4
      ipv6
      ipv6rs
      ia_na 0

Output is

    dhcpcd-10.0.5 starting
    chrooting as dhcpcd to /var/lib/dhcpcd
    sandbox: seccomp
    spawned manager process on PID 2806
    spawned privileged proxy on PID 2807
    spawned controller proxy on PID 2808
    DUID 00:01:00:01:2d:07:4c:cf:52:54:00:d8:9f:1b
    eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks PREINIT
    eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks CARRIER
    eth0: IAID 00:d8:9f:1b
    eth0: IA type 3 IAID 00:00:00:00
    eth0: adding address fe80::6258:2d14:1762:c497
    eth0: pltime infinity, vltime infinity
    eth0: delaying IPv6 router solicitation for 0.5 seconds
    eth0: delaying DHCPv6 for LL address
    eth0: delaying IPv4 for 1.0 seconds
    eth0: soliciting an IPv6 router
    eth0: delaying Router Solicitation for LL address
    eth0: reading lease: /var/lib/dhcpcd/eth0.lease
    eth0: soliciting a DHCP lease
    eth0: sending DISCOVER (xid 0x78ea5584), next in 3.9 seconds
    eth0: spawned BPF BOOTP on PID 2813
    eth0: offered 172.17.119.16 from 172.17.119.1
    eth0: process BPF BOOTP already started on pid 2813
    eth0: sending REQUEST (xid 0x78ea5584), next in 4.6 seconds
    eth0: acknowledged 172.17.119.16 from 172.17.119.1
    eth0: spawned BPF ARP 172.17.119.16 on PID 2814
    eth0: probing address 172.17.119.16/24
    eth0: probing for 172.17.119.16
    eth0: ARP probing 172.17.119.16 (1 of 3), next in 1.8 seconds
    eth0: reading lease: /var/lib/dhcpcd/eth0.lease6
    eth0: soliciting a DHCPv6 lease
    ps_root_recvmsg: Bad file descriptor
    eth0: delaying SOLICIT6 (xid 0x9c3cae), next in 1.0 seconds
    eth0: spawned DHCP6 proxy fe80::6258:2d14:1762:c497 on PID 2815
    eth0: sending Router Solicitation
    eth0: multicasting SOLICIT6 (xid 0x9c3cae), next in 1.1 seconds
    ps_root_recvmsg: Bad file descriptor
    eth0: ARP probing 172.17.119.16 (2 of 3), next in 1.2 seconds
    eth0: multicasting SOLICIT6 (xid 0x9c3cae), next in 2.3 seconds
    ps_root_recvmsg: Bad file descriptor
    eth0: ARP probing 172.17.119.16 (3 of 3), next in 2.0 seconds
    eth0: sending Router Solicitation
    ps_root_recvmsg: Bad file descriptor
    eth0: multicasting SOLICIT6 (xid 0x9c3cae), next in 4.4 seconds
    ps_root_recvmsg: Bad file descriptor
    eth0: DAD completed for 172.17.119.16
    eth0: leased 172.17.119.16 for 86400 seconds
    eth0: renew in 43200 seconds, rebind in 75600 seconds
    eth0: writing lease: /var/lib/dhcpcd/eth0.lease
    eth0: adding IP address 172.17.119.16/24 broadcast 172.17.119.255
    eth0: adding route to 172.17.119.0/24
    eth0: adding default route via 172.17.119.1
    eth0: ARP announcing 172.17.119.16 (1 of 2), next in 2.0 seconds
    eth0: executing: /usr/lib/dhcpcd/dhcpcd-run-hooks BOUND
    forked to background

**Comment by rsmarples** [comment]
This should be fixed in the master branch already. Can you test to make sure please?

**Comment by rsmarples** [comment]
Possible dup of #260 and #262

**Comment by hpresnall** [comment]
Confirmed after building master.
Configured with:

    ./configure \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --libexecdir=/usr/lib/$pkgname \
    --dbdir=/var/lib/$pkgname \
    --rundir=/run/dhcpcd \
    --runstatedir=/run/dhcpcd \
    --enable-ipv6 \
    --enable-privsep \
    --enable-seccomp \
    --without-dev \
    --without-udev

I think all the processes are running but still see the bad file descriptor messages.

     3206 dhcpcd    0:00 dhcpcd: eth0 
     3207 root      0:00 dhcpcd: [privileged proxy] eth0
     3208 dhcpcd    0:00 dhcpcd: [control proxy] eth0
     3214 dhcpcd    0:00 dhcpcd: [BPF ARP] eth0 172.17.119.16
     3215 dhcpcd    0:00 dhcpcd: [DHCP6 proxy] fe80::5054:ff:fef5:54af
     3235 dhcpcd    0:00 dhcpcd: [BOOTP proxy] 172.17.119.16

Also confirmed no issues if configured with --disable-privsep.

This is a very minimal VM, is there possibly an APK I need to install to enable everything in Alpine that's not covered by the current dhcpcd dependencies? To build, I only installed `git make automake autoconf gcc linux-headers bsd-compat-headers alpine-sdk`.

**Comment by rsmarples** [comment]
This is similar to #167 because you have disabled IPv6 in the global scope there is no inet proxy service for it.
I suppose we can try and find a proxy address to send the message from, but the kernel is *much* better placed to work that out.

**Comment by hpresnall** [comment]
Confirmed no errors on 10.0.5 when I removed `noipv6` from the global scope. I see a DHCP6 proxy process running for all the ipv6 addresses on the interface.

For reference, my config was probably overkill since I am running separate dhcpcd processes for each interface anyway using ifupdown-ng. But, I was being paranoid and disabling everything globally then reenabling for each iface.

However, why did dhcpcd error if `ipv6` was enabled for the interface. Is this an ordering issue related to when privsep starts processes vs parsing config? Maybe dhcpcd should warn and ignore `noipv6` in the global scope when privsep is configured?

**Comment by rsmarples** [comment]
It's a double edged sword.

IPv6 is designed for a single entity to control it. I have to go through a lot of hoops to get >1 dhcpcd instance to work with IPv6 on separate interfaces because that's how some people want and expect it to work.
It would be a lot easier and simpler if I ripped that out and just supported a single instance.

**Comment by hpresnall** [comment]
Closing this since it's a configuration issue with an easy workaround.

I will look into reconfiguring my setup to use a single dhcpcd instance that starts at boot rather than via ifupdown-ng.
