### ISSUE TITLE
Multiple ARP Probes within DEFEND_INTERVAL cause statically configured interfaces to be pulled down

### ISSUE THREAD

**Issue by pradeep-brightsign** [NetworkConfiguration/dhcpcd#272]
Setup: A very large network with statically configured devices.

Description: There are multiple devices on the network that send ARP probes. If 2 requests happen to be within the DEFEND_INTERVAL, the interface is brought down as a conflict resolution mechanism. This opens all our devices to a DoS attack.

Issue: We believe that this behavior is not in conformance with the RFC. Specifically section 2.4 (c).
https://datatracker.ietf.org/doc/html/rfc5227#section-2.4

   (c) If a host has been configured such that it should not give up its
       address under any circumstances (perhaps because it is the kind
       of device that needs to have a well-known stable IP address, such
       as a link's default router or a DNS server) then it MAY elect to
       defend its address indefinitely.  If such a host receives a
       conflicting ARP packet, then it should take appropriate steps to
       log useful information such as source Ethernet address from the
       ARP packet, and inform an administrator of the problem.  The
       number of such notifications should be appropriately controlled
       to prevent an excessive number of error reports being generated.
       If the host has not seen any other conflicting ARP packets
       recently, within the last DEFEND_INTERVAL seconds, then it MUST
       record the time that the conflicting ARP packet was received, and
       then broadcast one single ARP Announcement, giving its own IP and
       hardware addresses.  Having done this, the host can then continue
       to use the address normally without any further special action.
       However, if this is not the first conflicting ARP packet the host
       has seen, and the time recorded for the previous conflicting ARP
       packet is within DEFEND_INTERVAL seconds, then the host MUST NOT
       send another defensive ARP Announcement.  This is necessary to
       ensure that two misconfigured hosts do not get stuck in an
       endless loop flooding the network with broadcast traffic while
       they both try to defend the same address.

The Fix: We have a fix where we just log the conflict and keep holding the address when multiple conflicts happen within a defend interval. We believe this behavior is more in conformance with the RFC.

I have attached our patch, please advice if this patch is suitable for a merge back into upstream.

[dhcpcd-Ignore-ARP-probes-for-statically-assigned-IP.patch](https://github.com/NetworkConfiguration/dhcpcd/files/13716026/dhcpcd-Ignore-ARP-probes-for-statically-assigned-IP.patch)

**Comment by rsmarples** [comment]
Well, you have 3 sections, a b and c. All are MAY. Basically the implementer can pick one.
a is stop everything.
b is defend and then stop on fail - this is what dhcpcd currently does.
c is notify and carry on - this is what you want.

You can disable ARP by adding `noarp` to /etc/dhcpcd.conf to get the stable address - you lose the defense, but as ARP is not checked you don't lose the address.
Neither solution actually helps because if two hosts have the same IP address there is no guarantee you're talking to the host you really want.

I wonder if this is better served by adding an option to ARP to say "keep the address if defense fails" rather than just relying on a static binding because you could also have a reservation on the DHCP server for a static address as well.

**Comment by pradeep-brightsign** [comment]
Thanks @rsmarples.

I will go ahead with your suggestion of "keep the address if defense fails" and we, for our application, can then apply the option only when interfaces are statically configured. Do you have any suggestions what that option might be called? `arpdefenceretainip` - just made that up but please advice if you have a better one. Thanks

**Comment by rsmarples** [comment]
`arp_persistdefence` I think. It has more meaning than simply persisting the address.
You can set `DHCPCD_ARP_PERSISTDEFENCE (1ULL << 6)` in `if-options.h` for the option as that's free.
Don't forget to update the man page and bump it's date!

**Comment by rsmarples** [comment]
As a side note, if you use NetBSD then you have ARP defence in the kernel and the address is marked `IN_IFF_DUPLICATED` rather than being deleted which is the best you can possibly have. This allows existing connections to work and future ones not to, same as for IPv6 addresses.

**Comment by pradeep-brightsign** [comment]
@rsmarples, I am unable to create a pull request. Is it possible for you to provide me with access to the repo to create a branch and create a pull request? Thanks.

**Comment by rsmarples** [comment]
No.

Using GitHub, you fork this repository to your account and then clone it. Make a branch and changes there and then push to GitHub. You can then created a pull request from there.

**Comment by pradeep-brightsign** [comment]
Here is the pull request:
https://github.com/NetworkConfiguration/dhcpcd/pull/273

Thanks.

**Comment by pradeep-brightsign** [comment]
Thanks @rsmarples.

I have a question from my colleague. Do you think a flag like 'arp_nopersistdefence' will have any use? Possibly can be used to enable default defence behaviour?

**Comment by rsmarples** [comment]
That would only have a use of you wanted that behaviour in the global scope and wanted to negate it for a specific interface. Maybe someone could use it, but im not that sure of it's use as this new flag is pretty niche as it is.

Still, if you want to add it and document that it's the default behaviour I dont see any issue.
