### ISSUE TITLE
INFORM6 messages are never accepted from dhcrelay

### ISSUE THREAD

**Issue by hpresnall** [NetworkConfiguration/dhcpcd#277]
I am seeing continuous INFORM6  requests in the logs when starting dhcpcd on a server that talks to a dhcp server through dhcrelay:

    Dec 28 17:31:58 user daemon.debug dhcpcd[6738]: eth0: requesting DHCPv6 information
    Dec 28 17:31:58 user daemon.debug dhcpcd[6738]: eth0: delaying INFORM6 (xid 0x349b69), next in 1.0 seconds
    Dec 28 17:31:59 user daemon.debug dhcpcd[6738]: eth0: multicasting INFORM6 (xid 0x349b69), next in 1.1 seconds
    Dec 28 17:32:00 user daemon.debug dhcpcd[6738]: eth0: multicasting INFORM6 (xid 0x349b69), next in 2.3 seconds
    Dec 28 17:32:02 user daemon.debug dhcpcd[6738]: eth0: multicasting INFORM6 (xid 0x349b69), next in 4.2 seconds
    Dec 28 17:32:06 user daemon.debug dhcpcd[6738]: eth0: multicasting INFORM6 (xid 0x349b69), next in 8.5 seconds
    Dec 28 17:32:08 user daemon.debug dhcpcd[6738]: eth0: failed to request DHCPv6 information
    Dec 28 17:32:08 user daemon.debug dhcpcd[6738]: eth0: requesting DHCPv6 information

I am running dhcpcd 10.0.6 with the `ipv6` and `ipv6rs` options. The router sets the managed flag to off, so INFORM is expected. The dhcp server doesn't provide ipv6 addresses but does provide DNS search lists.

I can see messages as expected in tcpdump output:

    17:14:00.190098 eth0  Out IP6 (flowlabel 0x2cebe, hlim 1, next-header UDP (17) payload length: 52) fe80::5054:ff:fe7a:6238.546 > ff02::1:2.547: [udp sum ok] dhcp6 inf-req (xid=4957c2 (client-ID hwaddr/time type 1 time 756756214 5254007a6238) (option-request DNS-server DNS-search-list lifetime Client-FQDN opt_82 opt_83) (elapsed-time 106))
    17:14:00.193048 eth0  In  IP6 (flowlabel 0x75905, hlim 64, next-header UDP (17) payload length: 111) fe80::5054:ff:fe81:fdff.547 > fe80::5054:ff:fe7a:6238.546: [udp sum ok] dhcp6 reply (xid=4957c2 (client-ID hwaddr/time type 1 time 756756214 5254007a6238) (server-ID hwaddr/time type 1 time 756752960 525400334d18) (DNS-server fd27:0:0:1::2) (DNS-search-list user.home.local. home.local.))

Note that I am using dhcrelay because this server is in a different vlan than the dhcp server. When I try from a server with the same configuration on the same vlan as the dhcp server, there is no issue. Why would a relay cause this issue? The configuration seems to be correct as the reply is making it back to the dhcpcd server.

**Comment by rsmarples** [comment]
I have no idea why a relay would not work.
How are you starting dhcpcd? What is the output of `ps axu | grep dhcpcd`?

**Comment by hpresnall** [comment]
Should have looked at that a long time ago. It was in a weird state with a non-manager process was still running on eth0. Killing that and starting a manager process at boot fixed that issue.

Would starting dhcpcd at boot, before carrier on eth0, cause accept_ra to be set to 0? I am using ifupdown-ng's `use ipv6-ra` setting for that interface and I confirmed that ifup calls `echo 1 > /proc/sys/net/ipv6/conf/eth0/accept_ra` before dhcpcd starts. But after boot, everything is configured correctly except no router advertisements are being received because the param is set back to 0. I think this will make dhcpcd delete the route eventually.

**Comment by rsmarples** [comment]
In your first comment you note that you use dhcpcd's `ipv6rs` option. This is also the default and causes dhcpcd to disable the kernel from doing it. This sets `accept_ra` to zero. You don't want both handling the RA.
