### ISSUE TITLE
BUG: dhcpcd 10.0.6 - in if_setup_inet6() check for DHPCD_IPV6RS needs to occur BEFORE disabling the kernel

### ISSUE THREAD

**Issue by TG-Zubby** [NetworkConfiguration/dhcpcd#301]
void
if_setup_inet6(const struct interface *ifp)
{
   struct dhcpcd_ctx *ctx = ifp->ctx;
   int ra;
   char path[256];
 
   /* The kernel cannot make stable private addresses.
    * However, a lot of distros ship newer kernel headers than
    * the kernel itself so sweep that error under the table. */
   if (if_disable_autolinklocal(ctx, ifp->index) == -1 &&
       errno != ENODEV && errno != ENOTSUP && errno != EINVAL)
      logdebug("%s: if_disable_autolinklocal", ifp->name);

=======> this check needs to get moved before the call to if_disable_autolinklocal()
    * If not doing autoconf, don't disable the kernel from doing it.
    * If we need to, we should have another option actively disable it.
    */
   if (!(ifp->options->options & DHCPCD_IPV6RS))
      return;

**Comment by rsmarples** [comment]
You've not said what the current code is doing wrong and what the correct outcome looks like for your use case.

**Comment by TG-Zubby** [comment]
And I quote: "in if_setup_inet6() check for DHPCD_IPV6RS needs to occur BEFORE disabling the kernel"

**Comment by TG-Zubby** [comment]
FYI:  This comment is out of date, as the linux kernel has supported stable private for quite a while now.

/* The kernel cannot make stable private addresses.
* However, a lot of distros ship newer kernel headers than
* the kernel itself so sweep that error under the table. */
