### ISSUE TITLE
Please allow running as root

### ISSUE THREAD

**Issue by bdrung** [NetworkConfiguration/dhcpcd#305]
dhcpcd is used in the initramfs in Ubuntu. `ps_init` from `dhcpcd` will spit out this warning in case there is no busybox included it the initramfs:
```
getpwnam: No such file or directory
```
If busybox is included in the initramfs, the error message from `ps_init` changes to:
```
no such user dhcpcd
```
Please add an option to the dhcpcd command line to allow skipping `ps_init`.

**Comment by rsmarples** [comment]
Sounds like you need to ensure /etc/passwd and /etc/group exist in your initramfs with the dhcpcd user and a valid group.
The home directory for the dhcpcd user should point to an empty directory.

**Comment by perkelix** [comment]
> Sounds like you need to ensure /etc/passwd and /etc/group exist in your initramfs with the dhcpcd user and a valid group. The home directory for the dhcpcd user should point to an empty directory.

Ubuntu currently imports the Debian package as-is. Upon installation, we create a system user as follow:

`adduser --system --gecos "DHCP Client Daemon" --home /usr/lib/dhcpcd --no-create-home --shell /bin/false dhcpcd`

If there's a better way of doing this, I'm listening.

**Comment by rsmarples** [comment]
> Ubuntu currently imports the Debian package as-is. Upon installation, we create a system user as follow:
> 
> `adduser --system --gecos "DHCP Client Daemon" --home /usr/lib/dhcpcd --no-create-home --shell /bin/false dhcpcd`
> 
> If there's a better way of doing this, I'm listening.

That's 100% fine for the normal userland package.

If there is tooling to manage your initramfs image something similar needs to be done there I guess?
Sounds like OP is managing a custom image anyway as I doubt dhcpcd would be added to one by default.

**Comment by perkelix** [comment]
> > Ubuntu currently imports the Debian package as-is. Upon installation, we create a system user as follow:
> > `adduser --system --gecos "DHCP Client Daemon" --home /usr/lib/dhcpcd --no-create-home --shell /bin/false dhcpcd`
> > If there's a better way of doing this, I'm listening.
> 
> That's 100% fine for the normal userland package.
> 
> If there is tooling to manage your initramfs image something similar needs to be done there I guess? Sounds like OP is managing a custom image anyway as I doubt dhcpcd would be added to one by default.

OP is an Ubuntu developer. Ubuntu uses a large initramfs image and calls dhcpcd with the --oneshot option to perform a rough network configuration already at that bootup stage. For more complex situations, they launch Netplan or Network-Manager at later boot stages.

**Comment by rsmarples** [comment]
I stand corrected then :)

Still, the solution to the reported issue is still the same.
Any public facing daemon should not run as root, even for a one shot rough setup.

**Comment by perkelix** [comment]
@bdrung The first error you reported (getpwnam: No such file or directory) probably needs to be fixed in dhcpcd's code, if at all possible. However, for the second one, privsep simply cannot work without creating a non-root user.

**Comment by rsmarples** [comment]
dhcpcd doesn't need any fix.
`getpwnam: No such file or directory` means that /etc/passwd does not exist.
When adding busybox to the initramfs image it probably creates /etc/passwd somehow hence the different error.

**Comment by perkelix** [comment]
> dhcpcd doesn't need any fix. `getpwnam: No such file or directory` means that /etc/passwd does not exist. When adding busybox to the initramfs image it probably creates /etc/passwd somehow hence the different error.

Noted.

**Comment by bdrung** [comment]
Thanks. I will test copying `/etc/passwd` into the initramfs.

**Comment by bdrung** [comment]
Adding `/etc/passwd` into the initramfs was enough. Thanks for the help!
