### ISSUE TITLE
Release 6.11.7 missing from GitHub

### ISSUE THREAD

**Issue by andreaslarfors** [NetworkConfiguration/dhcpcd#31]
Hi! We're using version 6.11.7 of dhcpd (from here: http://roy.marples.name/git/dhcpcd/commit/32ecbd429a7b3911b6763cb4e4b06b0b40f84270 ) but the commits that make up this release appear to not have made it to GitHub.

Are you accepting Pull Requests? I could try to merge the commits in to retroactively tag & release 6.11.7... 
(if someone knows exactly how to do this that would be much appreciated!)

Thanks,
Andreas

**Comment by ido** [comment]
I will look into this today. Thanks for flagging it.

**Comment by rsmarples** [comment]
I've pushed the missing branches from my main repo to here and created the missing tag for dhcpcd-6.11.7.

Does this fix it for you?

Sorry @ido  I think the old branches got lost from github and I didn't realise.

**Comment by rsmarples** [comment]
https://github.com/NetworkConfiguration/dhcpcd/releases/tag/dhcpcd-6.11.7 works for me now.

**Comment by ido** [comment]
Thanks @rsmarples! I'm going to do a full sync of your self-hosted repos (already mirrored locally) and GitHub later today in case there are any more missing commits.

**Comment by rsmarples** [comment]
@ido there are two branches I deliberately missed - the ia branch was stale work in progress and the DNA branch is even older and I'm not sure DNA (RFC 4436) is something we even want to support as we store leases by SSID for wireless and wired won't change much.

**Comment by ido** [comment]
I added the DNA and ia branches as tags for posterity here, and otherwise think we now have everything from your local git repositories.  @andreaslarfors, I think that resolves it so I'm closing the issue for now, but please reopen if you need anything else.
