### ISSUE TITLE
Release only IPv4 or IPv6 address

### ISSUE THREAD

**Issue by MadaraCx** [NetworkConfiguration/dhcpcd#311]
If I want to release the leased IP addresses I use `dhcpcd -k eth0`, but this will release both IPv6 and IPv4 addresses.
Is there a way to only relase the IPv4 or IPv6 address, without releasing the other?

**Comment by MadaraCx** [comment]
This does not seem to work. `dhcpcd -k -4 eth0 ` and  `dhcpcd -k -6 eth0 `  removes both IPv4 and IPv6 lease addresses.

**Comment by rsmarples** [comment]
OK, that's a bug. I've replicated it and will work on a fix.

**Comment by rsmarples** [comment]
@MadaraCx can you test the above please?

**Comment by perkelix** [comment]
@MadaraCx ping

**Comment by MadaraCx** [comment]
Sorry, did not check this account for a while. Is there an installation I can test this with?
