### ISSUE TITLE
dhcpcd - ps_sendcmdmsg: Connection refused / ps_inet_recvbootp: Connection refused / dhcpcd.service: State 'stop-sigterm' timed out. Killing. / dhcpcd.service: Failed with result 'signal'.

### ISSUE THREAD

**Issue by luckylinux** [NetworkConfiguration/dhcpcd#315]
I am having several problems on one host (Raspberry Pi 2) where no matter what I try (in terms of `denyinterfaces` in `/etc/dhcpcd.conf`, setting `static` or `manual` for my `wlan0` in `/etc/network/interfaces.d/wlan0`, etc) it just won't start correctly.

The Rock 5B SBC, with the same configuration (but different static IP addresses of course) works flawlessly.

I am connected to my "Main LAN" on `eth0` both for the Raspberry Pi 2 and the Rock 5B.
`wlan0` is a Alfa Network AWUS1900 (RTL8814AU) USB Wireless Adapter that I use with `hostapd` and `dnsmasq` for some ESP32 and similar Network-of-Things Devices.

After the last update on the Raspberry Pi, everything stopped working.
The/Some devices kinda seem to be able to get an association with `hostapd` and IP address from `dnsmasq`. But most of them cannot be pinged from the AP itself (nor can I ping the AP when I connect a Desktop Client wirelessly to test).

Logs on the Raspberry Pi with `journalctl -xeu dhcpcd`:
```
Apr 13 07:50:06 RaspberryPi2 systemd[1]: Starting dhcpcd.service - DHCP Client Daemon on all interfaces...
░░ Subject: A start job for unit dhcpcd.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit dhcpcd.service has begun execution.
░░ 
░░ The job identifier is 93.
Apr 13 07:50:08 RaspberryPi2 dhcpcd[485]: dhcpcd-9.4.1 starting
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: dev: loaded udev
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: DUID 00:01:00:01:2d:82:ac:35:b8:27:eb:21:8b:02
Apr 13 07:50:08 RaspberryPi2 systemd[1]: Started dhcpcd.service - DHCP Client Daemon on all interfaces.
░░ Subject: A start job for unit dhcpcd.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit dhcpcd.service has finished successfully.
░░ 
░░ The job identifier is 93.
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: eth0: IAID eb:21:8b:02
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: ps_ctl_listen: read: Success
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: ps_ctl_recv: read: Success
Apr 13 07:50:08 RaspberryPi2 dhcpcd[586]: ps_sendpsmmsg: Connection refused
Apr 13 07:50:08 RaspberryPi2 systemd[1]: dhcpcd.service: Main process exited, code=killed, status=31/SYS
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStart= process belonging to unit dhcpcd.service has exited.
░░ 
░░ The process' exit code is 'killed' and its exit status is 31.
Apr 13 07:50:40 RaspberryPi2 dhcpcd[586]: ps_sendcmdmsg: Connection refused
Apr 13 07:50:40 RaspberryPi2 dhcpcd[586]: ps_inet_recvbootp: Connection refused
Apr 13 07:50:41 RaspberryPi2 systemd[1]: dhcpcd.service: State 'stop-sigterm' timed out. Killing.
Apr 13 07:50:41 RaspberryPi2 systemd[1]: dhcpcd.service: Killing process 586 (dhcpcd) with signal SIGKILL.
Apr 13 07:50:41 RaspberryPi2 systemd[1]: dhcpcd.service: Failed with result 'signal'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit dhcpcd.service has entered the 'failed' state with result 'signal'.
```

Routing also does NOT work properly on the Raspberry Pi.
The Output of `ip route` and/or `route -n` is **completely** different compared to Rock 5B.

Rock 5B correctly sets up routes & metrics also based on the Static Routes it receives from SHCP Option 121 (RFC3442):
```
default via 192.168.1.1 dev eth0 proto dhcp src 192.168.4.10 metric 1002 
169.254.0.0/16 dev eth1 scope link src 169.254.72.50 metric 1003 
172.22.0.0 dev eth0 proto dhcp scope link src 192.168.4.10 metric 1002 
172.22.0.0/16 dev wlan0 proto dhcp scope link src 172.22.1.1 metric 3004 
172.27.0.0/16 via 192.168.4.31 dev eth0 proto dhcp src 192.168.4.10 metric 1002 
192.168.0.0/20 dev eth0 proto dhcp scope link src 192.168.4.10 metric 1002 
192.168.254.0 dev eth0 proto dhcp scope link src 192.168.4.10 metric 1002 
192.168.254.0/24 dev eth1 proto kernel scope link src 192.168.254.1
```

Raspberry Pi gets the Static Routes it receives from SHCP Option 121 (RFC3442) but doesn't set up any metric or device associated with it:
```
default via 192.168.1.1 dev eth0 
172.22.0.0/16 via 192.168.4.10 dev eth0 
172.27.0.0/16 via 192.168.4.31 dev eth0 
172.27.0.0/16 dev wlan0 proto kernel scope link src 172.27.1.1 
192.168.0.0/20 dev eth0 proto kernel scope link src 192.168.4.31 
192.168.254.0/24 via 192.168.4.10 dev eth0 
```

Running `traceroute` on AP clients from the Rock 5B resolves immediately (as it should be), while on the Raspberry Pi 2 it seems to loop to itself (probably due to the missing metrics of the static route it seems to prefer to go back to the default route, then back to itself, then it doesn't seem to know where to go from there).

**Comment by rsmarples** [comment]
This looks like your libc was upgraded and uses different syscalls from what dhcpcd allowed at the time.
Can you test dhcpcd-10.0.6 please as that will likely work?

**Comment by luckylinux** [comment]
I was just transferring everything from a Raspberry Pi 2 (arm32/v7) to a Raspberry Pi 4 (arm64/v8).

This issue was driving me nuts ! I lost so much sleep yesterday :100:.

I am running with dhcpcd 9.4.1-24~deb12u3 on the Rock 5B and Raspberry Pi 4 with no issues.

One **potential** culprit was that I am APT pinning (on ALL these systems) libglib2.0-0 (currently 2.78.4-1) since `conmon` (which is needed by `podman`) uses it (otherwise it would still run the old version of `conmon` since its newer dependencies wouldn't be satisfied).

All systems have `libc6` 2.36-9.

I can give a try to `dhcpcd` the newer version from APT pinning to testing though: https://packages.debian.org/search?keywords=dhcpcd&searchon=names&suite=all&section=all.

**Comment by luckylinux** [comment]
Alright ... So

Contents of `/etc/apt/preferences.d/dhcpcd` (`dhcpcd-base` must also be included):
```
# Allow upgrading only my-specific-software from the testing release
Package: dhcpcd dhcpcd-base
Pin: release a=testing
Pin-Priority: 600
```

Version info from `/usr/sbin/dhcpcd --version`:
```
dhcpcd 10.0.6
Copyright (c) 2006-2023 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH PRIVSEP

```

And
```
root@RaspberryPi2:~ # systemctl status dhcpcd
● dhcpcd.service - DHCP Client Daemon on all interfaces
     Loaded: loaded (/lib/systemd/system/dhcpcd.service; enabled; preset: enabled)
     Active: active (running) since Sat 2024-04-13 12:49:26 CEST; 7s ago
       Docs: man:dhcpcd(8)
    Process: 18317 ExecStart=/usr/sbin/dhcpcd -q -b (code=exited, status=0/SUCCESS)
   Main PID: 18319 (dhcpcd)
      Tasks: 5 (limit: 1569)
        CPU: 485ms
     CGroup: /system.slice/dhcpcd.service
             ├─18319 "dhcpcd: [manager] [ip4] [ip6]"
             ├─18320 "dhcpcd: [privileged proxy]"
             ├─18321 "dhcpcd: [network proxy]"
             ├─18322 "dhcpcd: [control proxy]"
             └─18336 "dhcpcd: [BPF ARP] eth0 192.168.4.31"

Apr 13 12:49:26 RaspberryPi2 dhcpcd[18320]: eth0: soliciting an IPv6 router
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: soliciting a DHCP lease
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: offered 192.168.4.31 from 192.168.1.7
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: ignoring offer of 192.168.4.31 from 192.168.1.8
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: leased 192.168.4.31 for 3600 seconds
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: adding route to 192.168.0.0/20
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: adding default route via 192.168.1.1
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: adding route to 172.27.0.0/16 via 192.168.4.31
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: adding route to 172.22.0.0/16 via 192.168.4.10
Apr 13 12:49:27 RaspberryPi2 dhcpcd[18320]: eth0: adding route to 192.168.254.0/24 via 192.168.4.10
```

Also routes seem far more reasonable in `ip route`:
```
default via 192.168.1.1 dev eth0 proto dhcp src 192.168.4.31 metric 1002 
172.22.0.0/16 via 192.168.4.10 dev eth0 proto dhcp src 192.168.4.31 metric 1002 
172.27.0.0/16 via 192.168.4.31 dev eth0 proto dhcp src 192.168.4.31 metric 1002 
192.168.0.0/20 dev eth0 proto dhcp scope link src 192.168.4.31 metric 1002 
192.168.254.0/24 via 192.168.4.10 dev eth0 proto dhcp src 192.168.4.31 metric 1002
```

But I still don't get it ... The version of `libc6` and `libglib2.0-0` are the same on all Systems. Only difference is one system is 32 bit.

The other possibility is that, this is a "stock" Raspberry Pi, but lately I enabled Debian Bookworm official Repositories (which according to Debian Wiki it's supported, unlike on Raspberry Pi 1 armhf/armel thing).

It didn't seem like it upgraded much at all (maybe from Package version x.x.x-1 to x.x.x-1u or something like that).

**Comment by rsmarples** [comment]
It might well be that the 32-bit libc uses different syscalls to the 64-bit libc.
The important thing is that your problem is now solved though yes and we can close this?

**Comment by luckylinux** [comment]
Yes we can close this :+1: .

I am now not running on the Raspberry Pi 2 anymore, but at least I'm not getting that message anymore.
