### ISSUE TITLE
please release dhcpcd 10.0.7

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#322]
It's been 5 months since the last release. Given the plethora of commits sitting in Git, it would be desirable to immediately release what we have as 10.0.7, in concordance with the "release early, release often" principle.

**Comment by rsmarples** [comment]
Now I have #317 fixed this is possible. Things keep popping up which make me delay :/

**Comment by perkelix** [comment]
Thanks. Can we release what we have now and call it a day?

**Comment by rsmarples** [comment]
dhcpcd-10.0.7 is now out, enjoy!

**Comment by perkelix** [comment]
Thanks! :)
