### ISSUE TITLE
9.4.1-24 on 32 bit rasperrypOS Bookworm

### ISSUE THREAD

**Issue by sodakat** [NetworkConfiguration/dhcpcd#323]
Journal:

audit[749]: SECCOMP auid=4294967295 uid=106 gid=65534 ses=4294967295 pid=749 comm="dhcpcd" exe="/usr/sbin/dhcpcd" sig=31 arch=40000028 syscall=384 compat=1 ip=0xf7df6330 code=0x0

dhcpcd.service: Main process exited, code=killed, status=31/SYS

From what I can tell it appears systemd is killing the process because getrandom was called.

dhcpcd is started as a service.  I tried updating the systemd unit file to allow this syscall but it still gets killed.

Any hints appreciated.

**Comment by rsmarples** [comment]
This is fixed in the latest 9.5.1 and 10.0.6 releases already.
https://github.com/NetworkConfiguration/dhcpcd/commit/645c32dd1a511527b7eb88443a28dfe7704d5f52
