### ISSUE TITLE
please uncomment "option ntp_servers" in stock dhcpcd.conf

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#331]
It would be nice if "option ntp_servers" would be uncomented in the dhcpcd.conf we ship whenever any NTP client was found by ./configure.

**Comment by rsmarples** [comment]
It would, but then a few BSD's would complain that it's going beyond what a default DHCP client is expected to do to /etc
You can always enable by default in Debian if you wish.

**Comment by borkra** [comment]
It's not just a problem for debian but for Embedded Linux (Yocto, Buildroot) as well. It would be nice to operate from configure options in automatic manner instead of having to postprocess config file and uncomment code in hooks

**Comment by rsmarples** [comment]
That just puts post-processing the config file elsewhere.
