### ISSUE TITLE
Wi-FI Roaming no longer works

### ISSUE THREAD

**Issue by borkra** [NetworkConfiguration/dhcpcd#335]
We restested change from #228 and original code works and new one does not, could you please revert 4f5c499

**Comment by rsmarples** [comment]
I'm loath to just revert it, because we lose why we did it. I've added a patch above with commentary which might fix it for you? I can't test wireless atm, can you test please?

**Comment by rsmarples** [comment]
Ah, could you also describe how it's broken please? I forget what the expectations are here.

**Comment by borkra** [comment]
The change was made on my request, because of some issues reported and we could not test it at a time, I could not get access to it.

High level what I am observing triggering wireless roaming results in No Carrier instead No carrier roaming. I reverted the patch and it strated to work as expected. Reverting the patch again.

I can print out flags again and start low level debugging...

**Comment by rsmarples** [comment]
@borkra ok, I a new patch which "fixes" it. I tested it, by setting flags |= IFF_DORMANT in both if_roaming() and if_carrier_from_flags() in if-linux.c and dhcpcd behaves as expected.

Please test this branch (not a patch on anything else please) and if it doesn't work then we need to do some debugging to work out why it's not working.

**Comment by borkra** [comment]
Unfortunately, does not work, below is   the log of roaming event.

Original logic does.

```
dhcpcd[578]: dhcpcd-10.0.8 starting
dhcpcd[584]: wlan0: waiting for carrier
dhcpcd[584]: wlan0: carrier acquired
dhcpcd[584]: wlan0: connected to Access Point: XXXXXXXX
dhcpcd[584]: wlan0: soliciting a DHCP lease
dhcpcd[584]: wlan0: offered 192.168.1.203 from 192.168.1.1
dhcpcd[584]: wlan0: probing address 192.168.1.203/24
dhcpcd[584]: wlan0: leased 192.168.1.203 for 43200 seconds
dhcpcd[584]: wlan0: adding route to 192.168.1.0/24
dhcpcd[584]: wlan0: adding default route via 192.168.1.1
dhcpcd[584]: wlan0: carrier lost
dhcpcd[584]: wlan0: deleting route to 192.168.1.0/24
dhcpcd[584]: wlan0: deleting default route via 192.168.1.1
dhcpcd[584]: wlan0: carrier acquired
dhcpcd[584]: wlan0: soliciting a DHCP lease
dhcpcd[584]: wlan0: offered 192.168.1.203 from 192.168.1.1
dhcpcd[584]: wlan0: probing address 192.168.1.203/24
dhcpcd[584]: wlan0: leased 192.168.1.203 for 43200 seconds
dhcpcd[584]: wlan0: adding route to 192.168.1.0/24
dhcpcd[584]: wlan0: adding default route via 192.168.1.1
```

**Comment by borkra** [comment]
I add printout for flag transition during roaming, and IFF_DORMANT never get set (maybe something different with newer kernels or supplicant), again original logic worked

I added printouts of flag transition during roaming:
```
dhcpcd[548]: if_carrier_from_flags: flags 0x10049
dhcpcd[548]: if_carrier_from_flags: flags 0x11043
dhcpcd[548]: if_carrier_from_flags: flags 0x1003
dhcpcd[548]: if_roaming: flags 0x1003
dhcpcd[548]: wlan0: waiting for carrier
dhcpcd[548]: if_carrier_from_flags: flags 0x11003
dhcpcd[548]: if_roaming: flags 0x1003
dhcpcd[548]: if_carrier_from_flags: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x11003
dhcpcd[548]: wlan0: carrier acquired
dhcpcd[548]: wlan0: connected to Access Point: BKQQ3672
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: wlan0: soliciting a DHCP lease
dhcpcd[548]: wlan0: offered 192.168.1.203 from 192.168.1.1
dhcpcd[548]: wlan0: probing address 192.168.1.203/24
dhcpcd[548]: wlan0: leased 192.168.1.203 for 43200 seconds
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x1003
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: wlan0: adding route to 192.168.1.0/24
dhcpcd[548]: wlan0: adding default route via 192.168.1.1
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: if_carrier_from_flags: flags 0x11003
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x11003
dhcpcd[548]: wlan0: carrier lost
dhcpcd[548]: if_roaming: flags 0x11003
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x1003
dhcpcd[548]: wlan0: deleting route to 192.168.1.0/24
dhcpcd[548]: wlan0: deleting default route via 192.168.1.1
dhcpcd[548]: if_roaming: flags 0x11003
dhcpcd[548]: if_carrier_from_flags: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x11003
dhcpcd[548]: wlan0: carrier acquired
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: wlan0: soliciting a DHCP lease
dhcpcd[548]: wlan0: offered 192.168.1.203 from 192.168.1.1
dhcpcd[548]: wlan0: probing address 192.168.1.203/24
dhcpcd[548]: wlan0: leased 192.168.1.203 for 43200 seconds
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: if_roaming: flags 0x1003
dhcpcd[548]: if_roaming: flags 0x11043
dhcpcd[548]: wlan0: adding route to 192.168.1.0/24
dhcpcd[548]: wlan0: adding default route via 192.168.1.1
dhcpcd[548]: if_roaming: flags 0x11043
```

**Comment by borkra** [comment]
The reason original logic worked is because IFF_DORMANT was never used due to missing definition

**Comment by borkra** [comment]
My understanding there are 2 types of Roaming WPA supplicant initiated roaming, when it occurs you will get IFF_DORMANT, but then there is Wi-Fi firmware initiated roaming, for the ICs that support roaming offload, then IFF_DORMANT does not show.

**Comment by borkra** [comment]
I would propose:

```
bool
if_roaming(struct interface *ifp)
{
	return
#if defined(IFF_DORMANT)
	ifp->flags & IFF_DORMANT ||
#endif
#if defined(IFF_LOWER_UP)
	(ifp->flags & (IFF_UP|IFF_LOWER_UP|IFF_RUNNING)) == (IFF_UP|IFF_LOWER_UP) ||
#endif
	false;
}
```

**Comment by rsmarples** [comment]
OK, I added your proposed change with some commentary on the issue as it's certainly not clear. Please test to make sure it works for you as I removed a forced define if IFF_LOWER_UP as I can now include linux/if.h for the defines :)

**Comment by borkra** [comment]
Ok, now roaming works, but few other issues:

1. After roaming I get changing route to the one that is already there why, it does not need to change anything?
```
dhcpcd[542]: wlan0: carrier lost - roaming
dhcpcd[542]: wlan0: changing route to 192.168.1.0/24
dhcpcd[542]: wlan0: changing default route via 192.168.1.1
```
2. Looking at the code, now we have roaming logic twice, once in if_carrier_from_flags and the other one in if_roaming, it's redundant. The only reason to consider IFF_DORMANT is for roaming there is no other purpose, as well as other parts of the logic in it. I believe if_carrier_from_flags can go back to:
```
static int if_carrier_from_flags(unsigned int flags)
{
	return flags & IFF_RUNNING ? LINK_UP : LINK_DOWN;
}
```
3. Original problem probably was that IFF_DORMANT is never considered in the calculation, dues to header file and logic issues.

**Comment by rsmarples** [comment]
> Ok, now roaming works, but few other issues:

Great!

>     1. After roaming I get changing route to the one that is already there why? it does not need to change anything.
>        Actually the whole purpose of roaming logic is to preserve routing tables, so that TCP connections do not get aborted.
> 
> 
> ```
> dhcpcd[542]: wlan0: carrier lost - roaming
> dhcpcd[542]: wlan0: changing route to 192.168.1.0/24
> dhcpcd[542]: wlan0: changing default route via 192.168.1.1
> ```

We change the default metric for the route so we can prefer active non roaming interfaces.
On linux this involves adding a new route with the new metric and then deleting the old route with the old metric.

My testing at the time showed that TCP sessions such as SSH persist just fine.

https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/route.c#L389

> 
>     3. Looking at the code, now we have roaming logic twice, once in if_carrier_from_flags and the other one in if_roaming, it's redundant. 

It's a safety check.
If we have IFF_RUNNING AND IFF_DORMANT which should we believe?
I think it's fine as is.

>     4. Original problem probably was that IFF_DORMANT is never considered in the calculation, dues to header file and logic issues.

Now it is considered, both for the carrier state in regards to dhcpcd and the roaming state.

I don't think these are any deal breakers? Your actual issue here is solved yes, so anything else is just a matter of opinion?

**Comment by borkra** [comment]
Well, I cannot find it causing an issue at this time except for redundancy. If we find one I will let you know.
