### ISSUE TITLE
Can DHCP Server detect client windows version? 

### ISSUE THREAD

**Issue by javad9505** [NetworkConfiguration/dhcpcd#338]
I have a DHCP server and several clients, some running Windows 10 and some Windows 7. I want the DHCP server to be able to identify the Windows version of the clients using the vendor class and assign the settings I've specified accordingly. Also, I don't want to configure anything on the clients; I want the DHCP server to be able to detect the Windows version by itself. Is there a way to do this?

**Comment by perkelix** [comment]
dhcpcd is not a DHCP server. It is a DHCP client. Additionally, it doesn't run on Windows.

**Comment by rsmarples** [comment]
@javad9505 you probably want to refer to the kea project for DHCP server questions.
This is a dhcp client :)
