### ISSUE TITLE
dhcpcd obtaining an IP, and immediately loses the IP

### ISSUE THREAD

**Issue by bin456789** [NetworkConfiguration/dhcpcd#339]
I have a VPS with a newly installed Arch Linux system, which means all software packages are up to date.
I found that dhcpcd does not work properly. Specifically, after obtaining an IP, it immediately loses the IP and this process repeats. 
However, using systemd-networkd or network-manager works perfectly fine.
Here are the captured packets and logs when using different DHCP clients.
[caps.zip](https://github.com/user-attachments/files/16175549/caps.zip)

VPS IP: 
154.17.224.X/32
2a:10:76:f4:18:e9

Gateway IP: 
193.41.250.250
be:6f:9f:44:a0:02

Package Versions:
dhcpcd 10.0.8-1
systemd 256.2-1
networkmanager 1.48.4-1

If testing on this VPS is needed, I can provide full access. But only within the next few days.

**Comment by perkelix** [comment]
This is expected. You have 3 DHCP clients competing for control over the interface. Pick one and purge the other two.

**Comment by bin456789** [comment]
No, I only run one DHCP client each time I test.

**Comment by jvfranklin** [comment]
The dhcpcd.cap file shows you have an IP address conflict. Your mac is 2a:10:76:f4:18:e9, right? Packet 61 is a device with mac be:6f:9f:44:a0:02 that is responding to arps with the same IP you just got. So dhcpcd is declining the lease (packet 64).

**Comment by bin456789** [comment]
> The dhcpcd.cap file shows you have an IP address conflict. Your mac is 2a:10:76:f4:18:e9, right? Packet 61 is a device with mac be:6f:9f:44:a0:02 that is responding to arps with the same IP you just got. So dhcpcd is declining the lease (packet 64).

Seems right.
But if there really is an IP conflict, it shouldn't just be dhcpcd refusing to lease.

**Comment by jvfranklin** [comment]
Your own packet captures are showing the conflict. If you disagree with that assessment, please provide an alternative explanation.  As for networkd and network manager, you'll need to talk to those developers about implementing DAD. It's not a DHCP requirement that a client support it, but they might be willing to.

**Comment by jvfranklin** [comment]
I'm guessing be:6f:9f:44:a0:02 is your router/DHCP server? It seems to be acting strangely.  In network-manager.cap packet 61, it's sending gratutious arps for your IP address.  You can see the same thing happening in dhcpcd.cap at #61.

**Comment by bin456789** [comment]
> I'm guessing be:6f:9f:44:a0:02 is your router/DHCP server? 

Yes


> Your own packet captures are showing the conflict. If you disagree with that assessment, please provide an alternative explanation. As for networkd and network manager, you'll need to talk to those developers about implementing DAD. It's not a DHCP requirement that a client support it, but they might be willing to.

It seems that IP conflict detection is enabled by default for both `network-manager` and `systemd-networkd`
https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#DuplicateAddressDetection=
https://www.networkmanager.dev/docs/api/latest/settings-ipv4.html#:~:text=has%20no%20effect.-,dad%2Dtimeout,-int32

I also manually set the value of  `network-manager` ipv4.dad-timeout, and  still obtain the IP address normally.


```
[root@Host-By ~]# nmcli connection show ens18 | grep dad
ipv4.dad-timeout:                       200
```

**Comment by bin456789** [comment]
Thank you for providing the workaround. @rsmarples 

I also tested `dhclient` and it could also obtain an IP address normally.
I thought they were mature DHCP clients, at least they appeared relatively early.
It seems that dhcpcd won this round.

**Comment by rsmarples** [comment]
dhclient is *only* a DHCP client, nothing more, nothing less. It's very limited outside of this and has no ARP checking itself so never sees this issue.

**Comment by jvfranklin** [comment]
Not to mention dhclient went EOL a year and a half ago, though it was a pretty solid app.  We're replacing it with dhcpcd in our product now, and dhcpcd seems to be a lot better. It's a lot smaller in size than dhclient, and is miles ahead of networkd in terms of correct DHCPv6 behavior.  I wouldn't recommend networkd for anything.

**Comment by perkelix** [comment]
Funny you'd say that. Distros all seem very keen on migrating to networkd.

**Comment by jvfranklin** [comment]
They're probably not testing its IPv6 conformance.

**Comment by perkelix** [comment]
They're not testing for anything. They're merely going for whatever software is currently popular.

**Comment by rsmarples** [comment]
> Funny you'd say that. Distros all seem very keen on migrating to networkd.

These would be the systemd based ones changing from networkmanager to networkd.
I don't see any loss here. I mean it makes sense, once you make the bed with systemd you might sleep in all of it.
