### ISSUE TITLE
DHCP address not being assigned

### ISSUE THREAD

**Issue by RogueWarrior65** [NetworkConfiguration/dhcpcd#34]
I've been trying to set up dhcpcd (v8.0.3) on a Yocto-based system.  Ironically, it works great for setting up static IP addresses which is what most people are having trouble with.  However, in my case, I'm unable to get it to handle DHCP addressing. 

I keep seeing "waiting for 3rd party to configure IP address" messages in the systemd service status but I have no idea what this 3rd party is. 

Here's the dhcpcd.conf:

hostname
clientid
persistent
option rapid_commit
option domain_name_servers, domain_name, domain_search, host_name
option classless_static_routes
option interface_mtu
option ntp_servers
require dhcp_server_identifier
slaac private
nohook lookup-hostname
denyinterfaces p2p*
noipv6
noipv6rs
noarp

interface wlan0
static ip_address=
static routers=

interface enp1s0
static ip_address=
static routers=

interface eth0
static ip_address=192.168.0.50/24
static routers=192.168.0.1

Here's the output from "ip a" as requested:

root@ts-imx6:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: can0: <NOARP,ECHO> mtu 16 qdisc noop state DOWN group default qlen 10
    link/can
3: can1: <NOARP,ECHO> mtu 16 qdisc noop state DOWN group default qlen 10
    link/can
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:d0:69:52:15:0f brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.50/24 brd 192.168.0.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
5: enp1s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 00:d0:69:52:15:10 brd ff:ff:ff:ff:ff:ff
6: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether 84:25:3f:5e:df:1e brd ff:ff:ff:ff:ff:ff
7: p2p0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 3000
    link/ether 86:25:3f:e4:df:1e brd ff:ff:ff:ff:ff:ff
8: p2p-p2p0-0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 3000
    link/ether 86:25:3f:e5:df:1e brd ff:ff:ff:ff:ff:ff
    inet 192.168.4.1/24 brd 192.168.4.255 scope global p2p-p2p0-0
       valid_lft forever preferred_lft forever

Here's the systemctl status output:
(FYI, I also have dnsmasq running which conflicts with the systemd-resolve service which is why there are fail messages.  If I enable that service, there's no change in the main problem of obtaining a DHCP address)

root@ts-imx6:~# systemctl status dhcpcd.service

* dhcpcd.service - dhcpcd on all interfaces
   Loaded: loaded (/lib/systemd/system/dhcpcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2021-04-27 19:41:28 UTC; 33s ago
  Process: 390 ExecStart=/sbin/dhcpcd -q -w (code=exited, status=0/SUCCESS)
 Main PID: 501 (dhcpcd)
    Tasks: 2
   Memory: 5.6M
   CGroup: /system.slice/dhcpcd.service
           |-442 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0
           `-501 /sbin/dhcpcd -q -w

Apr 27 19:41:24 ts-imx6 dhcpcd[390]: wlan0: carrier acquired
Apr 27 19:41:24 ts-imx6 dhcpcd[390]: wlan0: waiting for 3rd party to configure IP address
Apr 27 19:41:24 ts-imx6 dhcpcd[390]: Failed to revert interface configuration: Unit dbus-org.freedesktop.resolve1.service not found.
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: eth0: carrier acquired
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: eth0: using static address 192.168.0.50/24
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: eth0: adding route to 192.168.0.0/24
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: eth0: adding default route via 192.168.0.1
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: Failed to revert interface configuration: Unit dbus-org.freedesktop.resolve1.service not found.
Apr 27 19:41:28 ts-imx6 dhcpcd[390]: forked to background, child pid 501
Apr 27 19:41:28 ts-imx6 systemd[1]: Started dhcpcd on all interfaces.

**Comment by RogueWarrior65** [comment]
I think I may have figured it out.  Apparently systemd-networkd.service wasn't enabled and running.
I'm going to confirm that things are working as expected tomorrow.  If this is the case, I suggest that some clarification in the documentation about how dhcpcd overrides networkd interface file settings (or /etc/network/interfaces for that matter) might help others in the future.

**Comment by ido** [comment]
Thank you.  Looking forward for an update tomorrow. :-)

**Comment by rsmarples** [comment]
> interface wlan0
> static ip_address=
> static routers=
> 
> interface enp1s0
> static ip_address=
> static routers=

This is probably what causes the `waiting for 3rd party to configure IP address` message.
If you don't want dhcpcd to run on these interfaces, use the `allowinterfaces` or `denyinterfaces` directives.

**Comment by rsmarples** [comment]
> 
> 
> I think I may have figured it out. Apparently systemd-networkd.service wasn't enabled and running.
> I'm going to confirm that things are working as expected tomorrow. If this is the case, I suggest that some clarification in the documentation about how dhcpcd overrides networkd interface file settings (or /etc/network/interfaces for that matter) might help others in the future.

I disagree. dhcpcd should only document what it does with kernel and system files it directly touches. systemd and Debian network config are neither of these.
FWIW, I have a systemd install where networkd isn't running and it works just fine.

**Comment by RogueWarrior65** [comment]
Okay, this appears to be the solution.  I guess I was expecting dhcpcd to be handling the whole process of assigning IP addresses.  It does so for static IP addresses.

**Comment by borkra** [comment]
dhcpcd does handle all ip assigning functions, the same as systemd-networkd. If you enable both though they will start fighting each other and overwriting each other. systemd-networkd has DHCP client inside as well. You need to enable one or the other not both.

**Comment by RogueWarrior65** [comment]
Hmm... then why wasn't dhcpcd assigning addresses?  Is this some configuration setting I'm missing?

**Comment by borkra** [comment]
My guess because systemd - networkd hijacking the DHCP and/or statement in config file 'static ip_addreess=' is confusing dhcpcd, remove everything from config file you do not want to be set. Not assign to nothing but remove statements all together.

**Comment by RogueWarrior65** [comment]
Isn't leaving "static ip_address=" blank supposed to invoke a DHCP assignment?

**Comment by borkra** [comment]
Something you set in dhcpcd conf confused it, not sure what, you can start taking stuff out until it start working.

**Comment by ido** [comment]
Closing this issue as it seems to be resolved and/or specific misconfiguration on a specific host rather than a request to change/fix dhcpcd in some way.

**Comment by rsmarples** [comment]
> Isn't leaving "static ip_address=" blank supposed to invoke a DHCP assignment?

No, it's to indicate to dhcpcd that a 3rd party will assign the address.
The use case is a static setup when something like PPP assigns an address.

**Comment by RogueWarrior65** [comment]
Ah, ok, so in order to get dhcpcd to make the assignment, I would need to delete the lines with "static" in them, correct?  Or do I need to delete the entire interface block?  Ultimately, I'm working with another GitHub project called RaspAP which is a PHP front-end for handling a lot of network configuration on a Raspberry Pi.  That code is what's adding the interface blocks with blank static settings to /etc/dhcpcd.conf.  It's starting to sound like they're using dhcpcd incorrectly or they have another dependency that I'm not aware of.

In my case, I'm porting that project over to a Yocto-based system.  Enabling systemd-networkd.service fixes the problem for me.

**Comment by rsmarples** [comment]
Just delete the static lines.
You can have an empty interface block, but that might be confusing if you have many of them.
