### ISSUE TITLE
ps_seccomp_violation SIGSYS SYS_SECCOMP for statx

### ISSUE THREAD

**Issue by Jabrwock** [NetworkConfiguration/dhcpcd#348]
arm with glibc 2.35, libseccomp 2.5.3, dhcpcd 10.0.8

dhcpcd -U <interface> after successful lease

ps_seccomp_violation: unexpected syscall 397 (arch=0x40000028)

```
read(3, "reason=ROUTERADVERT\0interface=et"..., 382) = 382
statx(1, "", AT_STATX_SYNC_AS_STAT|AT_NO_AUTOMOUNT|AT_EMPTY_PATH, STATX_BASIC_STATS, {stx_mask=0, stx_attributes=STATX_ATTR_APPEND|STATX_ATTR_NODUMP|STATX_ATTR_ENCRYPTED|STATX_ATTR_AUTOMOUNT|STATX_ATTR_VERITY|0x1b6c30000, stx_mode=0176137, stx_size=3066496609, ...}) = 1
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0xb6c61ae6, si_syscall=__NR_statx, si_arch=AUDIT_ARCH_ARM} ---
write(2, "ps_seccomp_violation: unexpected"..., 63ps_seccomp_violation: unexpected syscall 397 (arch=0x40000028)
) = 63
exit_group(1)                           = ?
+++ exited with 1 +++
```

Adding statx to SECCOMP_ALLOW in privsep-linux resolves the issue, I'll upload a patch.

**Comment by rsmarples** [comment]
dhcpcd does not use libseccomp

**Comment by rsmarples** [comment]
@Jabrwock I can't see any issue with your patch, but I am confused as to why a statx call is being made. dhcpcd won't call stat(2) or statx(2) for the -U path at all. Certainly on debian using `strace dhcpcd -U` I don't see it - using glibc-2.36.
