### ISSUE TITLE
DHCPv6 and DNSMASQ problem

### ISSUE THREAD

**Issue by borkra** [NetworkConfiguration/dhcpcd#35]
The problem is that all currently released versions of dnsmasq do not support dhcpv6 rebind message. It's is fixed already in development tree, but it will be a while before it will be released and propagate through all the installations, I wonder if some workaround could be offered in dhcpcd for this.

**Comment by ido** [comment]
If I understood correctly, the problem will be solved by either not using dnsmasq, or waiting until dnsmasq does another release...

**Comment by borkra** [comment]
The problem is that dnsmasq has large installation footprint.
I am not in control of network device is on, or what customers are using for DHCP server.

So the fact that dnsmasq is fixed will have little bearing on the problem in years to come, until everybody updates.

And large IT organizations are very conservative in changing network hardware.
The only grace, I hope though majority customers will use Cisco routers as DHCP server.

I hope this issue could be fixed.

**Comment by ido** [comment]
Can you point me to the dnsmasq commit that resolves the bug and any other
documentation or discussion you have on it?  I’ll do some reading, but my
current inclination is to close as wontfix because this is a slippery slope
as far as complexity goes.

**Comment by borkra** [comment]
Here is the commit:

https://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=d55e2d086d1ff30c427fa5e0ecc79746de8a81b7

**Comment by borkra** [comment]
The original problem was when device went through reboot without releasing DHCPv6 address, when it comes back up IPv6 not received. 

I have conversation with Roy on the mailing list, why IPv6 is not released from DHCPv6 server, and Roy helped me with adding release flag to the conf file. Unfortunately, release fixes the problem on graceful shutdown, but not on ungraceful one, like yanking power cord. The other part of the issue, why dhcpcd could not get IPv6 address back after reboot. My understanding that was due to rebind message problem with dnsmasq.

My hope is you could add something like if REBIND message timed out (not acked withing certain time send renew or something like it)

**Comment by ido** [comment]
1. When you are in the failed rebind state (e.g. after ungraceful shutdown
and failure to reacquire IP), does the running dhcpcd with the --renew
option get you an IP address (without killing dhcpcd)?
2. Can you share the debug output from dhcpcd when it fails to reacquire an
IPv6 address?

**Comment by rsmarples** [comment]
> I have conversation with Roy on the mailing list, why IPv6 is not released from DHCPv6 server, and Roy helped me with adding release flag to the conf file. Unfortunately, release fixes the problem on graceful shutdown, but not on ungraceful one, like yanking power cord.

Nothing stops you from manually deleting the lease file before dhcpcd starts or during the PREINIT hook if you want it scripted.
That should force a fresh DISCOVER each time dhcpcd starts.

> The other part of the issue, why dhcpcd could not get IPv6 address back after reboot. My understanding that was due to rebind message problem with dnsmasq.
> 
> My hope is you could add something like if REBIND message timed out (not acked withing certain time send RENEW or something like it)

That is not RFC compliant. REBIND happen *after* RENEW times out or when a link comes up with lease containing a Prefix Delegation.
Sending a RENEW during REBIND might confuse some servers.
If REBIND times out then the lease is discarded and we enter the DISCOVER phase.

On carrier up, if we REBIND a DHCPv4 lease then the timeouts are be shortened to the reboot option in dhcpcd.conf, default of 5 seconds.
https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/if-options.h#L51

We might want to consider the same for DHCPv6 leases, maybe adding a timeout to dhcp6_startexpire here:
https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/dhcp6.c#L2720
