### ISSUE TITLE
clientid option for DHCPv6 is using MAC address of different interface

### ISSUE THREAD

**Issue by ChaoticRoman** [NetworkConfiguration/dhcpcd#354]
Hello!

I am playing with IPv6 recently and I would like to have fixed IPv6 address for given interface. My router supports that given the client use either DUID-LL or DUID-LLT. I have migrated to dhcpcd because it supports such option through `clientid`.

I got little confused because it have not worked, through it had before. Then, inspecting DHCPv6 Solicit packet using Wireshark, I have found that it uses MAC address of different interface on my computer... Even after removing USB Ethernet dongle with offending interface, and restarting NetworkManager it still kept memories of missing interface and in its honor it still used old undesired DUID-LLT derived from removed interface.

Is this expected? I would expect that it will use different DUID-LLT for every interface derived from that interface's MAC address.

UPDATE: Old DUID-LLT persisted even through restart.

**Comment by jvfranklin** [comment]
A DUID is global for an OS, basically. It's generated once and used forever, even if you swap out NICs and get completely new macs.  The IAID is specific to a given interface, so that should be different per interface. You'll probably find a segment of the interface's mac address in it.

The combination of DUID and IAID will uniquely identify every network interface on the planet.

**Comment by ChaoticRoman** [comment]
Thank you for prompt response. I was expecting something like that as I understand motivation behind DUID. The problem at hand is to get predictable static IPv6 address reservation for an interface on a host where various interfaces provide different services. I was hoping that this is going to make the trick. Seems I am overlooking something and I am on totally wrong track.

**Comment by jvfranklin** [comment]
I think it would just be a matter of figuring out how to refer to that client's DUID/IAID. It would be server-dependent, obviously. But have you considered just using SLAAC?  It'll give you consistent addresses, and any info you can't get from a router advertisement could be acquired via stateless DHCPv6.

**Comment by rsmarples** [comment]
> Thank you for prompt response. I was expecting something like that as I understand motivation behind DUID. The problem at hand is to get predictable static IPv6 address reservation for an interface on a host where various interfaces provide different services. I was hoping that this is going to make the trick. Seems I am overlooking something and I am on totally wrong track.

If the host only has one interface, is a fresh install and you ask for DUID-LL in dhcpcd.conf then the DUID and IAID combination sent is entirely predictable and thus reservations can be made. You can also set your own DUID by editing /var/db/dhcpcd/duid - dhcpcd won't change that file if it has something in the right format.

In this day and age though, do reservations even make sense?

**Comment by ChaoticRoman** [comment]
Verified and it works well. I have generated both DUID-LL and DUID-LLT ([small helpers to do it](https://github.com/ChaoticRoman/duid-generator)) and it both worked as expected with my router and provided GUI and API kit (the router is using ISC DHCPD with `hardware ethernet` option).

Only irregularity is that on my Ubuntu, the file was `/var/lib/dhcpcd/duid` instead of `/var/db/dhcpcd/duid`.

**Comment by rsmarples** [comment]
Yeah, linux distros change the default directories dhcpcd and I work with which are the BSD defaults.
