### ISSUE TITLE
output of --dumplease empty when reading from stdin and output redirected to file

### ISSUE THREAD

**Issue by diego-santacruz** [NetworkConfiguration/dhcpcd#356]
If I run
```
dhcpcd --dumplease -4 - < /var/lib/dhcpcd/eth0.lease > out
```
the output file `out` is empty, but if I run
```
dhcpcd --dumplease -4 - < /var/lib/dhcpcd/eth0.lease
```
the output on the terminal is fine.

I traced this to the fact that `printf` is used to write the output but stdout is not flushed, nor closed, before exiting. When stdout is a terminal it is line buffered by default, so everything works nicely, but when stdout is a file it is fully buffered by default, and thus nothing is written out before `dhcpcd` exits.

I experienced this on `dhcpcd` version 9.4.1, but I believe it applies to the latest version too.

**Comment by diego-santacruz** [comment]
I have created a patch for `dhcpcd` 9.4.1, that fixes the problem.

I forward ported to master, here it is [0001-dhcpcd-stdout-output-sometimes-empty-when-redirected.patch](https://github.com/user-attachments/files/16763893/0001-dhcpcd-stdout-output-sometimes-empty-when-redirected.patch)

**Comment by rsmarples** [comment]
Is not flushing stdout before exit enough? What's the need for the extra calls?

**Comment by diego-santacruz** [comment]
> Is not flushing stdout before exit enough? What's the need for the extra calls?

The flushing of stdout before exit should be enough, the others are more "belt & suspenders" in case the exit does not go through the expected code path (or in the future things are modified and other code paths appear), as I saw there are also other places in the code where there are "strategic" calls to `fflush()`

**Comment by rsmarples** [comment]
Fair enough.
Can you publish a pull request rather than a patch file please?
Just makes it easier to review and comment on it.

**Comment by diego-santacruz** [comment]
Sure, I'll do it, but I am traveling do it may take a bit of time.

**Comment by diego-santacruz** [comment]
Sorry for the delay, I have just created the PR #364 with the fix.

**Comment by rsmarples** [comment]
Merged, thanks
