### ISSUE TITLE
Functional requirement: Add parameter support to select nd address

### ISSUE THREAD

**Issue by Sunser** [NetworkConfiguration/dhcpcd#358]
Advertise multiple prefixes on the router IPv6 interface, and the dhcpcd client will simultaneously add the broadcasted multiple prefixes to the interface
I have multiple interfaces in Linux, and I just want to choose to add an address with a different prefix to each interface. Can we consider adding a parameter in the configuration file to allow the client to fix the address of nd1_addrX and add it to the interface.
For example, adding a selectaddr 1 indicates adding the value of nd1_addr1 to the interface
Another interface setting is selectaddr 2, which means adding the value of nd1_addr2 to the interface

**Comment by rsmarples** [comment]
Sounds like you want DHCPv6 Prefix Delegation which supports this rather than ND which doesn't.
Does this help?

**Comment by Sunser** [comment]
ND is simpler, but for dhcpv6 prefix delegation, it is necessary to record the duid of each client for static allocation, which is more complex to operate compared to ND.
For example, my router br lan interface ND broadcast 2001::/68, 2002::/68, 2003::/68
Under normal circumstances, the client can obtain these 3 prefixes and add them to the network card. I want to implement filtering and deduplication for multiple network cards in the same physical environment, with each card having its own unique prefix. The main purpose of this is that each prefix corresponds to a WAN exit, and the program only uses the preferred address of each interface and not all addresses
effect, veth1 2001::xxxxx/68
veth2 2002::xxxxx/68
veth3 2004::xxxxx/68
The above content is from translation, and the meaning may not be expressed clearly enough

**Comment by rsmarples** [comment]
The meaning is quite clear.
You want Prefix Delegation functionality from ND.
I won't support this in dhcpcd code, but you could use the `noconfigure` option and dhcpcd will just log the nd1_addr options in the ROUTERADVERTISEMENT sent to the script. You could then write a hook to look at these variables and assign them to whatever interface you wanted to.

Does this help?

**Comment by Sunser** [comment]
Use the noconfigure option and then use hook to make it effective. It would be even better if it could be implemented in the underlying code

**Comment by rsmarples** [comment]
I'm not going to implement this, sorry.
