### ISSUE TITLE
With multiple interfaces, dhcpcd v10.0.6 sends wrong duid in dhcpv6 solicit

### ISSUE THREAD

**Issue by pgalbraith** [NetworkConfiguration/dhcpcd#365]
I have the following multihomed config for dhcpcd v10.0.6 on OpenBSD:

```
duid
persistent
vendorclassid
option interface_mtu
option host_name
option rapid_commit
require dhcp_server_identifier
slaac private
nohook resolv.conf
nogateway
ipv6ra_noautoconf
interface em0
        ia_na 0x5cf37401
        ia_pd 0x5cf37402 -
interface em1
        ia_na 0x5cf37501
        ia_pd 0x5cf37502 -
```

dhcpcd is working nicely on the em0 interface, but on the em1 interface I get no assigned address or prefix.  My ISP seems to be responding, and I've noticed that dhcpcd is sending the LL address and DUID of em0 (5c f3 **74**), rather than em1 (5c f3 **75**), when it sends out the solicit on em1.

![image](https://github.com/user-attachments/assets/eed1919a-621b-4a2e-b1b7-0d6d1f7ab2db)

**Comment by pgalbraith** [comment]
adding packet capture
[dhcpv6-em1.zip](https://github.com/user-attachments/files/17069354/dhcpv6-em1.zip)

**Comment by jvfranklin** [comment]
The DUID identifies a whole computer system, not an interface. The interface is identified by the IAID. So you would expect to see the same DUID in every DHCPv6 message dhcpcd sends.  It's a little different than DHCPv6 that way.

I think there's something else going on that's preventing the transaction from completing. Are there any dhcpcd logs that have an indication of why it's not accepting the Advertise?

**Comment by pgalbraith** [comment]
@jvfranklin thanks for the clarification, that clears things up.  I didn't see any obvious diagnostic message from dhcpcd in the logs, but I've since changed the iaid I'm using to simple 0 (on em0) and 1 (on em1), and things seem to be working now on both interfaces.  I'm not completely convinced the iaid was the problem, but I'm content to leave well enough alone!

**Comment by pgalbraith** [comment]
Hrmph, I spoke too soon, it's still not working reliably at all.  I've posted here, instead, in the hopes that someone might be able to look at the packet capture and see what is wrong.

https://github.com/NetworkConfiguration/dhcpcd/discussions/366
