### ISSUE TITLE
Router Adv DNSSL option should be an array 

### ISSUE THREAD

**Issue by sshambar** [NetworkConfiguration/dhcpcd#367]
RFC 8106 section 5.2 defines option 31 as an array of domain names, but src/dhcpcd-definitions.conf:424 has:
`embed		domain			search`
so when an array of domains is received in a RA, the server issues the error:
`dhcp_envoption 31.0/2: Invalid argument`

Changing line 424 to:
`embed		array domain		search`
results in correct handling of the search list.

Really easy fix :)

**Comment by rsmarples** [comment]
Thanks for the fix!
