### ISSUE TITLE
Prefix Delegation Expires Before Renewal

### ISSUE THREAD

**Issue by denradford** [NetworkConfiguration/dhcpcd#368]
Greetings

I've been having issues the past few weeks with the prefix delegation expiring well before the IPv6 NA address renewal.
I am running dhcpcd on my FreeBSD Internet router.
`FreeBSD 14.1-RELEASE-p5 GENERIC amd64`

<pre>dhcpcd 10.0.10
Copyright (c) 2006-2024 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH PRIVSEP</pre>

This is what the interfaces look like on dhcpcd first run, rebind, `dhcpcd -k`, `dhcpcd -n` as well as a normal dhcp6 renewal.

Note that the vltime of the delegated prefix is much smaller than the assigned na1 address.

<pre>re0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
        options=60241b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,LRO,WOL_MAGIC,RXCSUM_IPV6,TXCSUM_IPV6>
        ether 1c:6f:65:21:77:c7
        inet 68.xxx.xxx.248 netmask 0xfffffc00 broadcast 255.255.255.255
        inet6 fe80::1e6f:65ff:fe21:77c7%re0 prefixlen 64 scopeid 0x1
        inet6 2604:xxxx:xxxx:xxxx:1072:7bc3:bb22:cad3 prefixlen 128 pltime 172800 vltime 172800
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=1<PERFORMNUD>
sk0: flags=1008843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST,LOWER_UP> metric 0 mtu 1500
        options=80009<RXCSUM,VLAN_MTU,LINKSTATE>
        ether 00:1c:f0:ca:d4:4d
        inet 192.168.0.2 netmask 0xffff0000 broadcast 192.168.255.255
        inet6 fe80::21c:f0ff:feca:d44d%sk0 prefixlen 64 scopeid 0x2
        inet6 2604:xxxx:xxxx:126::1 prefixlen 64 pltime 41728 vltime 41728
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL></pre>

dhcpcd -U seems to show that both the na1 and pd1 have a matching lease vltime of 172800.

<pre>reason=RENEW6
interface=re0
protocol=dhcp6
dhcp6_client_id=000100012bd37a981c6f652177c7
dhcp6_server_id=0001000117ab55720050568b2c36
dhcp6_ia_na1_iaid=00000001
dhcp6_ia_na1_t1=86400
dhcp6_ia_na1_t2=138240
dhcp6_ia_na1_ia_addr1=2604:xxxx:xxxx:xxxx:1072:7bc3:bb22:cad3
dhcp6_ia_na1_ia_addr1_pltime=172800
dhcp6_ia_na1_ia_addr1_vltime=172800
dhcp6_ia_pd1_iaid=00000002
dhcp6_ia_pd1_t1=86400
dhcp6_ia_pd1_t2=138240
dhcp6_ia_pd1_prefix1_pltime=172800
dhcp6_ia_pd1_prefix1_vltime=172800
dhcp6_ia_pd1_prefix1_length=64
dhcp6_ia_pd1_prefix1=2604:xxxx:xxxx:126::

reason=DELEGATED6
interface=sk0
protocol=dhcp6
delegated_dhcp6_prefix=2604:xxxx:xxxx:126::1/64</pre>

Logged events show the early expiration of the prefix delegation. Followed by a normal na1 dhcp6 renewal as expected at 86400 (24 hours). The prefix delegation is restored, but again expiring in just 41728 (12 hours).

<pre>Sep 23 06:10:34 dhcpcd[15442]: sk0: pid 0 deleted address 2604:xxxx:xxxx:126::1/64
Sep 23 06:10:36 dhcpcd[15442]: lo0: changing reject route to 2604:xxxx:xxxx:126::/64 via ::1
Sep 23 18:35:04 dhcpcd[15442]: re0: 2604:xxxx:xxxx:126::/64 will expire before renewal
Sep 23 18:35:05 dhcpcd[15442]: sk0: adding address 2604:xxxx:xxxx:126::1/64
Sep 23 18:35:05 dhcpcd[15442]: sk0: changing route to 2604:xxxx:xxxx:126::/64</pre>

dhcpcd.conf
<pre>duid
vendorclassid
option interface_mtu
option rapid_commit
require dhcp_server_identifier

noipv6rs
denyinterfaces sk0

interface re0
        ipv6rs
        ia_na 1
        ia_pd 2 sk0/0</pre>

**Comment by rsmarples** [comment]
This should already be fixed in 6cb9e8b74f033afdf1b4f29cd5b9943268a32a60

**Comment by denradford** [comment]
After building and running your current master branch, I can confirm that the issue is indeed resolved by your recent commit(s).

Thank you!
