### ISSUE TITLE
Fallback to link-local address

### ISSUE THREAD

**Issue by yoonghm** [NetworkConfiguration/dhcpcd#37]
I am using Raspberry Pi OS (buster) and dhcpcd 8.1.2.  The Pi is connected to a laptop, running Microsoft Windows 10, using a crossed Ethernet cable.  The laptop Ethernet port is assigned 169.254.86.80, automatically.

I set up `/etc/dhcpcd.conf` like this:  
```
hostname
clientid
persistent
option rapid_commit
option interface-mtu
require dhcp_server_identifier
slaac private

interface eth0
arping 192.168.2.1
fallback mylan 

debug
logfile /home/pi/abc.log

profile 192.168.2.1
static ip_address=192.168.2.44/24
static routers=192.168.2.1
static domain_name_servers=192.168.2.1

profile mylan
static ip_address=169.254.1.1/16
static routers=169.254.0.1
static domain_name_servers=169.254.0.1
```

`/home/pi/abc.log` shows

```
...
...
eth0: ARP announcing 169.254.1.1 (1 of 2), next in 2.0 seconds
eth0: executing `/lib/dhcpcd/dhcpcd-run-hooks' STATIC
forking to background
forked to background, child pid 535
eth0: deleting IP address 169.254.1.1/16
eth0: deleting default route via 169.254.0.1
```

Something has triggered dhcpcd to delete 169.254.1.1. 

However, if I change the `mylan` profile to the following, the static IP address will be assigned.

```
profile mylan
static ip_address=192.168.1.11/24
static routers=192.168.1.1
static domain_name_servers=192.168.1.1
```

How do I use link-local address instead?

**Comment by ido** [comment]
Can you paste or attach the full log file including what comes after
deletion?

**Comment by yoonghm** [comment]
If I use link-local IP address, there is no more lines after that.
