### ISSUE TITLE
dumplease in exit-hook?

### ISSUE THREAD

**Issue by ColinMcInnes** [NetworkConfiguration/dhcpcd#390]
Is there a way to dump the lease (in human readable format via --dumplease) to a file from within an exit hook?

caveat is PRIVSEP is enabled.

Use case is logging leases for later review.

Example
```
/usr/libexec/dhcpcd-hooks/10-create-readable-lease
    dhcpcd --dumplease -4 "${interface}" >> "$LEASEFILE"
 ```

**Comment by rsmarples** [comment]
Not easily as dhcpcd will wait for the hook to exit before processing the sockets, so you create a recursive loop doing that.
However, the lease is decoded into environment variables and you could do something like this:

`set | sed -ne 's/^new_//p' | sort >> "$LEASEFILE"`

**Comment by ColinMcInnes** [comment]
Thank you
