### ISSUE TITLE
stdin lease is not read, current lease is read instead

### ISSUE THREAD

**Issue by ColinMcInnes** [NetworkConfiguration/dhcpcd#391]
Cannot use STDIN to load an older copy of the lease to decode it. It only fetches current lease.
dhcpcd 10.0.10, linux
dhcpcd is currently running in managed mode

PRIVSEP is enabled.
```
entra-rpd-9059945:/home/tier3support# dhcpcd -4 eth0
dhcpcd-10.0.10 starting
...
eth0: soliciting a DHCP lease
eth0: offered 192.168.228.153 from 192.168.228.21
eth0: probing address 192.168.228.153/24
eth0: leased 192.168.228.153 for 259200 seconds
eth0: adding route to 192.168.228.0/24
eth0: adding default route via 192.168.228.2

# dhcpcd  -4 eth0 -U
reason=BOUND
interface=eth0
protocol=dhcp
ip_address=192.168.228.153
subnet_cidr=24
broadcast_address=192.168.228.255
network_number=192.168.228.0
subnet_mask=255.255.255.0
routers=192.168.228.2
dhcp_lease_time=259200
dhcp_message_type=5
dhcp_server_identifier=192.168.228.21

# cp /var/lib/dhcpcd/eth0.lease /var/lib/dhcpcd/eth0.lease.backup

# dhcpcd -4 eth0 --rebind
sending signal HUP to pid 20300

# dhcpcd -4 eth0 -U
reason=RENEW
interface=eth0
protocol=dhcp
ip_address=192.168.228.153
subnet_cidr=24
broadcast_address=192.168.228.255
network_number=192.168.228.0
subnet_mask=255.255.255.0
routers=192.168.228.2
dhcp_lease_time=259200
dhcp_message_type=5
dhcp_server_identifier=192.168.228.21

# dhcpcd -4 eth0 -U < /var/lib/dhcpcd/eth0.lease
reason=RENEW
interface=eth0
protocol=dhcp
ip_address=192.168.228.153
subnet_cidr=24
broadcast_address=192.168.228.255
network_number=192.168.228.0
subnet_mask=255.255.255.0
routers=192.168.228.2
dhcp_lease_time=259200
dhcp_message_type=5
dhcp_server_identifier=192.168.228.21

# dhcpcd -4 eth0 -U < /var/lib/dhcpcd/eth0.lease.backup 
reason=RENEW
interface=eth0
protocol=dhcp
ip_address=192.168.228.153
subnet_cidr=24
broadcast_address=192.168.228.255
network_number=192.168.228.0
subnet_mask=255.255.255.0
routers=192.168.228.2
dhcp_lease_time=259200
dhcp_message_type=5
dhcp_server_identifier=192.168.228.21
```

**Comment by ColinMcInnes** [comment]
traced to read_lease, we check if the lease file name is populated, as opposed to existing. dhcp_init will always set this up.

recommend changing the behaviour to check if stdin has been redirected to a file, and if so, dumplease can use that as the source.

**Comment by rsmarples** [comment]
Replace interface name with `-` should work?

`dhcpcd -U4 - < /var/lib/dhcpcd/eth0.lease.backup`

**Comment by ColinMcInnes** [comment]
Yes, that works. Thank you!

Interface is still needed for it to print the two IPv6 protocols, otherwise it only prints out the dhcp6, and doesn't include the reason.

```
# dhcpcd -U6 - < eth0.lease6.1
dhcp6_ia_na1_iaid=48033e9a
dhcp6_ia_na1_t1=259200
dhcp6_ia_na1_t2=388800
dhcp6_ia_na1_ia_addr1=2001:192:168:900::345
...
```
```
# dhcpcd -U6 eth0 - < eth0.lease6.1
reason=ROUTERADVERT
interface=eth0
protocol=ra
nd1_from=fe80::2efa:a2ff:fe9c:14df
...

reason=REBOOT6
interface=eth0
protocol=dhcp6
dhcp6_ia_na1_iaid=48033e9a
....
```

**Comment by rsmarples** [comment]
> Yes, that works. Thank you!

Good!

> Interface is still needed for it to print the two IPv6 protocols, otherwise it only prints out the dhcp6, and doesn't include the reason.

We only store the DHCPv6 lease, not the RA.
So if you're seeing the RA by specifying the interface then it's reading it from the current dhcpcd process which is what you don't want!
You don't get the reason with the DHCPv4 lease so don't expect it with the DHCPv6 one.

**Comment by ColinMcInnes** [comment]
Yes, you're right, adding interface is short-circuiting stdin and is reading from current release. Not what I wanted. I will leave it off since the interface is in the DB file.

I hadn't realized the reason wasn't printed in DHCPv4 either, but I think I was using dumplease there incorrectly as well. I would like to be able to tell if the last lease was a rebind but I can log that from the exit hooks.
