### ISSUE TITLE
please set the hostname option in the provided dhcpcd.conf

### ISSUE THREAD

**Issue by frx-wintermute** [NetworkConfiguration/dhcpcd#393]
Hello,
I noticed that the provided ```dhcpcd.conf``` configuration file has the following option commented out:

  ```
  # Inform the DHCP server of our hostname for DDNS.
  #hostname
  ```

I also noticed that this used to be enabled in the past, but was commented out in commit 2a52d7b .
Why? For privacy reasons? In order to not reveal the hostname of the machine that makes a DHCP request on a network?

I think this option is useful. It would be nice, if it were re-enabled in the provided ```dhcpcd.conf``` file, so that DDNS could work out of the box, without the need to locally modify the configuration on each host where dhcpcd is installed.

I hope you will consider applying this modification.

Thanks for your time!

**Comment by rsmarples** [comment]
Yes, privacy.

There are other ways of doing DDNS outside of DHCP - mDNS is a good example.

**Comment by perkelix** [comment]
Isn't the IPV4LL implementation of dhcpcd supposed to do that? Of course, in its current form, it merely kicks in as a backup if DHCPv4 failed to return a usable connection so, unless I missed something, it could not work out of the box without uncommenting the above.

**Comment by rsmarples** [comment]
No, the IPv4LL just sets an IP address a default route.
mDNS works with any IP address, not just IPv4LL.

**Comment by perkelix** [comment]
This issue has been raised again at Debian. They consider it an RC bug because it breaks compatibility with what dhclient does. Would you consider reverting this and shipping the option uncommented?

**Comment by perkelix** [comment]
@rsmarples any news on this?
