### ISSUE TITLE
Buffer overrun possible in rfc3396_write?

### ISSUE THREAD

**Issue by billie-alsup** [NetworkConfiguration/dhcpcd#418]
I'm late to the party for reviewing https://github.com/NetworkConfiguration/dhcpcd/pull/383 but noticed it when integrating with our OpenEmbedded recipe.

It seems to me that rcs3396_write function misses a 2 byte adjustment of ctx->buflen to account for the added code and length bytes.  This could lead to the buffer overrun for certain cases.  If you're thinking rfc3396_write_byte or rfc3396_zero could fail, then I'd be suspicious that the buffer overrun had already occurred on a previous call to rfc3396_write.

**Comment by rsmarples** [comment]
Thanks for that!
