### ISSUE TITLE
dhcpcd 8.1.9 is unable to renew leases, causing network interruptions

### ISSUE THREAD

**Issue by kazikcz** [NetworkConfiguration/dhcpcd#45]
I've seen these discuss apparently the same problem:
- https://roy.marples.name/archives/dhcpcd-discuss/0003431.html
- https://roy.marples.name/archives/dhcpcd-discuss/0003395.html

The commits are invalid, and links are 404. I was able to bisect the renew problem to:
- initial regression
```
commit e14045cae2a4b66995a87bbc40c4516a00d4c087
Author: Roy Marples <roy@marples.name>
Date:   Tue Apr 21 09:55:50 2020 +0100

    align CMSG buffer
```

- regression fixed
```
commit 29024d0ba64010eb85ad0d164898b7751d47d1cb
Author: Roy Marples <roy@marples.name>
Date:   Sun Apr 26 21:05:06 2020 +0100

    Align more CMSG foo.
```

I have filed a ticket on Alpine Linux regarding this, wondering if dhcpcd-8 branch could be updated with a fix, or should dhcpcd-9 branch be considered:
- https://gitlab.alpinelinux.org/alpine/aports/-/issues/12900

Let me know what you think.

**Comment by rsmarples** [comment]
The links to the archives work fine for me?

Does the fix in #43 help solve the issue for you?

dhcpcd-8 isn't really supported much right now, dhcpcd-9 is the stable branch.

**Comment by Hello71** [comment]
@kazikcz the commits are valid, the cgit was taken down (i assume).

**Comment by rsmarples** [comment]
Indeed. I no longer self host and it was easier to get gitweb running on it.
https://roy.marples.name/git/dhcpcd works fine.

**Comment by kazikcz** [comment]
@rsmarples #43 doesn't really apply on 8.1.9. There's no src/privsep.c to begin with so I can't really test it, can I? Master branch works fine for me.

Interestingly, both ecb8f4b14de3ad9e8d0901db43269fd36c972123 and 002e7ccc2ade2379d4d5d1e8b9a5f6a3fc448d64 don't seem to be reachable when I clone https://roy.marples.name/git/dhcpcd. They seem to be detached from any branch/tag. I can locate the commits if I hand-edit links on gitweb though:
 - https://roy.marples.name/git/dhcpcd/commit/002e7ccc2ade2379d4d5d1e8b9a5f6a3fc448d64
 - https://roy.marples.name/git/dhcpcd/commit/ecb8f4b14de3ad9e8d0901db43269fd36c972123

Anyway, Alpine Linux bumped the dhcpcd package, and you're saying dhcpcd-8 isn't really supported - which is fine. I think it's fine to close the issue.

Thanks for the prompt response!
