### ISSUE TITLE
dhcp6_bind: wrong loglevel

### ISSUE THREAD

**Issue by rain0r** [NetworkConfiguration/dhcpcd#46]
(Title may be misleading / wrong)

This issue has its origin in the Gentoo Forums: [Link](https://forums.gentoo.org/viewtopic-p-8644068.html?sid=c460ba4bc9b45f2c6d49c7c5fb94be9b#8644068)

> the issue needs fixing here: https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/dhcp6.c#L3049

**Comment by rsmarples** [comment]
Sorry about the time taken!

Hopefully you can test the patch and let me know if it fixes for you or not. If it fixes fine then I'll push to dhcpcd-9

**Comment by rain0r** [comment]
Yes, that fixed the problem.

Thank you for your work.
