### ISSUE TITLE
Can't access Vendor-specific information (opt 17 ipv6) in the hookup script.

### ISSUE THREAD

**Issue by dburtnja** [NetworkConfiguration/dhcpcd#53]
Hi, 

DHCPv6 server in Advertise message sending the 17 option to dhcpcd client. It could be seen on the Wireshark screenshot:
![image](https://user-images.githubusercontent.com/24833381/131839819-572a7e7b-9c61-4e77-bc30-f61f29484eec.png)

But when I'm printing all available options in hookup script. Only Enterprise ID (_new_dhcp6_vivso_enterprise_number_) is available.
![image](https://user-images.githubusercontent.com/24833381/131840110-ee3c47f2-fdb4-4835-bed5-ec2543da2884.png)

 Do you know how can I get Vendor-specific option data?

B/R
Denys

**Comment by rsmarples** [comment]
You need to add instructions to dhcpcd.conf on how to decode it - dhcpcd has no idea about per enterprise options.
The dhcpcd.conf man page should have instructions for that.

**Comment by dburtnja** [comment]
Hi, thanks for the quick reply! 
As I learned from `man dhcpcd.conf` there is a possibility to request custom options, but I need to request existing one.
```
>dhcpcd -V
...
00017 vivso                             	 embed
...
```
 I've tried to overwrite the existing one (option 17) with command in dhcpcd.conf file
```
...
define6 17 encap vendor_encap
...
```
but it's not working. dhcpcd client doesn't request the 17 option from DHCP server. 
![image](https://user-images.githubusercontent.com/24833381/131988750-0edf8f99-9ade-410a-84ca-22f981770c90.png)
It is requesting it when I add `option vivso` into config file and remove `define6 17 encap vendor_encap`, but only part of it available in the hookup script (enterprise id).


I'm using:
```
dhcpcd 6.11.5
Copyright (c) 2006-2016 Roy Marples
Compiled in features: INET IPv4LL INET6 DHCPv6 AUTH
```

Do you have time to help me to solve my problem?

B/R
Denys

**Comment by dburtnja** [comment]
Oh, sorry, I've changed the instruction from `define6 17 encap vendor_encap` to `define6 17 request encap vendor_encap` and now it is requesting it.  My mistake!

But it can't be parsed, I will try to use another type.

**Comment by dburtnja** [comment]
Hi, the solution `define6 17 request binhex vendor_specific_info`. 

B/R
Denys
