### ISSUE TITLE
dhcpcd not picking up WAN IP change?

### ISSUE THREAD

**Issue by torrunes** [NetworkConfiguration/dhcpcd#75]
I have some devices "in the field" that either can be connected by a mobile modem or cabled Ethernet. dhcpcd is used to handle routing and resolv.conf and such. When the device is connected to WAN using a mobile connection, dhcpcd grabs the IP address from the modem and uses it to configure the interface. This works well at startup, and the modem usually keeps its originally assigned address during the power-on session. 

However, on rare and random(?) occasions, the modem loses its connection.Then the following can happen: 

- At reconnection, the modem gets another IP address
- The address change is not picked up by dhcpcd, so Linux will still use the old address, which of course is not working any longer. 

Example: 
Hardware: Intel Atom device, Sierra Wireless MC7304 USB modem.
Software: Linux kernel 4.9, Gentoo distro, dhcpcd 9.4.0, qmicli 1.30.2

The initial state is that the system has booted and is communicating as normal. Yesterday, the MNO had an outage (connection problems), so it was a perfect occasion to try to figure out the problem. After the outage had been resolved, some devices did not connect to the system before the next morning (new boot), or in a couple of hours while running. We have a logger service on the device to see what happens. 

This is 3 hours after the outage had been resolved:

_ip a_ 
7: wwp0s20u5u1i8: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
   link/none 
   inet **10.34.248.232**/28 brd 10.34.248.239 scope global dynamic noprefixroute wwp0s20u5u1i8
      valid_lft 3118sec preferred_lft 2218sec

_qmicli -p -d /dev/cdc-wdm0 --wds-get-current-settings_
[...]         IPv4 address: **10.83.127.99**

On another device, ip a showed no address for the WAN interface. (Could be that the lease had expired(?))

I don't know if this is a bug, a missing feature, or something actually not meant to be handled? Are there any fixes in newer dhcpcd versions, any config we should enable/disable, or any other suggestion? Customs scripting seems a viable solution in case dhcpcd actually shall not handle this situation "automagically".

**Comment by rsmarples** [comment]
dhcpcd just listens to interface state changes announces by the kernel.
https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/if-linux.c#L962
https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/if-linux.c#L1042

If an interface loses IFF_RUNNING then the "link is down" and dhcpcd will drop the lease for the interface.
Once connectivity is restored, IFF_RUNNING should be restored also and this is announced by the kernel.
When this happens, dhcpcd negotiates a new lease.

I don't know if your WAN interface does this or not or if dhcpcd needs to do something extra. Unsure why something extra would be needed though as this approach has been working fine since the 90's for other interfaces.

**Comment by borkra** [comment]
This is a known issue with QMI RawIP connection. It does not drop connection bit on disconnect. On LTE links there is no DHCP server on the network, IP information is provided during connection setup, statically through LTE protocol. DHCP server you connect is specific to QMI (if you switch modem into MBIM mode there will be no DHCP server any more), and located on the modem, it is serving this static IP to the client. 

Your best solution to reconnect issues is to use some modem management software like ModemManager or ofono.

**Comment by rsmarples** [comment]
Another alternative would be to run a shell script via cron to monitor the connection using `qmicli`.
If you think it's disconnected you could simulate a carrier signal to dhcpcd like so:
`ifconfig wwan0 down;`
Or use iproute2 or something.
Bring the interface up if you think it's reconnected, but you get the idea.

You could also bring dhcpcd down directly - `dhcpcd -x wwan0` and back up again `dhcpcd -n wwan0`.

**Comment by torrunes** [comment]
Thanks for the explanations and hints, both of you. 
Looking at your last hint, Roy, would the -x actually be needed, or could a -n suffice?

**Comment by rsmarples** [comment]
-x removes the lease and associated configuration. You should do this when the connection is down.
-n re-negotiates the lease and configured the host. You should do this when the connection is up.

Hope this helps!

**Comment by rsmarples** [comment]
Closing this as there is nothing dhcpcd can do to help. Maybe someone could write a note in a man page about it or on a wiki.
