### ISSUE TITLE
NTP hooks restart ntpd for no reason

### ISSUE THREAD

**Issue by nsayer** [NetworkConfiguration/dhcpcd#78]
On Raspberry Pis running Bullseye and dhcpcd 1:3.2.3-11, dhcpcd restarts ntpd on lease renewal even if the DHCP server does not announce NTP servers. This is detrimental, as the longer ntpd runs the better its control over clock drift and the longer the polling intervals with its peers become.

**Comment by nsayer** [comment]
Neutering 66-ntp.conf by commenting out the call to "handle_reason" at the bottom works around this issue successfully.

**Comment by rsmarples** [comment]
Are you entirely sure about this? dhcpcd-3.2.3 restarted NTP all the the in the C code not shell scripts as we do now.
dhcpcd-4 was the first dhcpcd to support restarting NTP and others via shell scripts.
dhcpcd-9.4.1 is the newest dhcpcd so no matter what you're way out of date. It also as code to ensure that NTP is only restarted *if* the configuration file dhcpcd wants to give it has changed from what it's currently using so this should be fixed if you upgrade?

**Comment by nsayer** [comment]
This is the most up-to-date version available for Raspbery Pi OS. The version number is what I got from apt info. If I do —version it says 8.1.2. It’s probably the same as Debian Bullseye, from which Pi OS is derived.

**Comment by rsmarples** [comment]
Can you try the hook scripts from the dhcpcd-9.4.1 release please? They at least seem to work fine and don't needlessly restart ntpd for me.

**Comment by nsayer** [comment]
I went back through the source tree and it's clear that somewhere downstream (debian or raspbian) of here the hooks have been completely rewritten.
