### ISSUE TITLE
Commit "eloop: Allow eloop to process all fds returned from  poll(2)" causing dhcpcd-gtk to loop endlessly on startup.

### ISSUE THREAD

**Issue by geki-yaba** [NetworkConfiguration/dhcpcd#79]
Tried 9.4.1 and dhcpcd-gtk 0.7.8 loops endlessly on startup with that commit[0].

[0] https://github.com/NetworkConfiguration/dhcpcd/commit/fe2b82eec25da908c3a1a71c2dc2402d9ff70e31

**Comment by geki-yaba** [comment]
die@deiwl:~$ dhcpcd-gtk 
Gtk-Message: 09:41:48.656: Failed to load module "canberra-gtk-module"

(dhcpcd-gtk:9145): Gtk-WARNING **: 09:41:48.690: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
** Message: 09:41:48.774: Connecting ...
** Message: 09:41:48.774: Status changed to opened
** Message: 09:41:48.774: Connected to dhcpcd-9.4.0
** Message: 09:41:48.774: Status changed to down

** (dhcpcd-gtk:9145): CRITICAL **: 09:41:48.774: dhcpcd_open: Ungültiger Dateideskriptor
** Message: 09:41:48.876: Status changed to opened
** Message: 09:41:48.876: Connected to dhcpcd-9.4.0
** Message: 09:41:48.877: Status changed to down
** Message: 09:41:48.878: Status changed to opened
** Message: 09:41:48.878: Connected to dhcpcd-9.4.0
** Message: 09:41:48.878: Status changed to down
...[SNIP]

**Comment by rsmarples** [comment]
That has already been reverted on the dhcpcd-9 branch in 2b4fe4c12b5d4366ff21fabf3a6c3799f8e4fa53.
The master branch seems to work fine with it I think.

**Comment by geki-yaba** [comment]
Right. Using 9.4 HEAD works. Closing.
