### ISSUE TITLE
how dhcpcd will  trigger kernel load modules such as rfkill&8021q

### ISSUE THREAD

**Issue by shixudong2020** [NetworkConfiguration/dhcpcd#91]
how dhcpcd will  trigger kernel load modules such as rfkill&8021q？

**Comment by rsmarples** [comment]
dhcpcd does not directly trigger loading of any kernel modules.

**Comment by shixudong2020** [comment]
please look my test,i use dhclient get dhcp,then i open two termianl.
first run 'sudo udevadm monotor',second run 'sudo systemctl start dhcpcd'(defalut is disable)
here is monitor log:
sxd@debian10:~$ sudo udevadm monitor
monitor will print the received events for:
UDEV - the event which udev sends out after rule processing
KERNEL - the kernel uevent

KERNEL[779.309549] add      /module/llc (module)
KERNEL[779.312758] add      /module/mrp (module)
UDEV  [779.314494] add      /module/llc (module)
KERNEL[779.315296] add      /module/stp (module)
UDEV  [779.318715] add      /module/mrp (module)
UDEV  [779.322245] add      /module/stp (module)
KERNEL[779.322616] add      /module/garp (module)
UDEV  [779.323874] add      /module/garp (module)
KERNEL[779.330172] add      /module/8021q (module)
UDEV  [779.331434] add      /module/8021q (module)
KERNEL[779.339865] add      /class/rfkill (class)
UDEV  [779.341195] add      /class/rfkill (class)
KERNEL[779.341499] add      /devices/virtual/misc/rfkill (misc)
UDEV  [779.343107] add      /devices/virtual/misc/rfkill (misc)
KERNEL[779.351997] add      /module/rfkill (module)
UDEV  [779.353925] add      /module/rfkill (module)
KERNEL[779.438240] add      /class/ieee80211 (class)
UDEV  [779.439735] add      /class/ieee80211 (class)
KERNEL[779.440406] add      /devices/platform/regulatory.0 (platform)
UDEV  [779.442345] add      /devices/platform/regulatory.0 (platform)
KERNEL[779.444379] add      /module/cfg80211 (module)
UDEV  [779.446390] add      /module/cfg80211 (module)

how dhcpcd indirectly or directly trigger kernel load modules such as rfkill&8021q？

**Comment by rsmarples** [comment]
So if dhcpcd wants to use an interface it will bring it up like `ifconfig eth0 up`. I suppose this may load kernel modules.

I'm really not sure what you're asking about anyway - there is no bug to fix here.

**Comment by shixudong2020** [comment]
i 'ls -al /sys/class/net',find only eth0 and lo

**Comment by rsmarples** [comment]
This is not a dhcpcd issue, it's a "how do kernel modules get loaded" question which should be taken elsewhere, like your distribution forums.
