### ISSUE TITLE
dhcpcd doesn't restore the oringinal value of addr_gen_mode when exiting

### ISSUE THREAD

**Issue by yizhao1** [NetworkConfiguration/dhcpcd#97]
dhcpcd sets addr_gen_mode=1 explicitly in function if_disable_autolinklocal() (src/if-linux.c).

The initial commit of if_disable_autolinklocal shows this is to avoid potentially duplicate link local addresses.

commit 78a67110452aade468f1bd13fd2cb409d0003b98
Author: Roy Marples <roy@marples.name>
Date: Mon Aug 11 20:52:39 2014 +0000

Set IFLA_INET6_ADDR_GEN_MODE to IN6_ADDR_GEN_MODE_NONE
for supporting kernels to avoid potentially duplicate
IPv6 link-local addresses.

But it doesn't restore the original value of addr_gen_mode when exiting. So the kernel can not set link local address to the network interface after dhcpcd exits. Here is the test case:
$ dhcpcd -6 -b --inform6 --noconfigure -Q dhcp_message_type -f /etc/dhcpcd.conf eth0
$ ifconfig eth0
$ sleep 90
$ dhcpcd -6 -k eth0

$ echo -n 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6
$ ifconfig eth0
$ sleep 90
$ echo -n 0 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6
$ sleep 90
$ ifconfig eth0

kernel can not generate IPv6 Link Local address. There are no inet6 entry such as fe80::dea6:32ef:ffc0:4567.

After set addr_gen_mode to 0, it works, kernel can generate IPv6 Link Local address.
$ echo 0 > /proc/sys/net/ipv6/conf/eth0/addr_gen_mode

**Comment by rsmarples** [comment]
dhcpcd is designed to be running all the time and addressing this would impact how I personally develop as then LL addresses would unexpectedly appear for me.

What is your use case for fixing this in a production environment?

**Comment by yizhao1** [comment]
Thanks. So far as I know, this is only a test case.
